<?php echo $this->headLink()->appendStylesheet('/css/contato.css') ?>

<ul id="globalnav">
  <li><a href="/pessoal/meusdados" >Meus Dados</a></li>
  <li><a href="/pessoal/edit" class="here" >Alterar Dados</a></li>
  <li><a href="/pessoal/imagem" >Nova Imagem</a></li>
  <li><a href="/pessoal/senha">Alterar Senha</a></li>
</ul>

<form id="createproject" class="rounded" action="/pessoal/edit" method="post">
        <div class="field">      
            <label for="nome">Nome:</label>
            <input type="text" class="input" id="nome" name="nome" maxlength="35" value ="<?= $this->funcionario->nome; ?>"/>
            <p class="hint">Insira o seu nome.</p>
        </div>

        <div class="field">      
            <label for="doc">Identidade:</label>
            <input type="text" class="input" id="doc" name="doc" maxlength="25" value ="<?= $this->funcionario->documentoIdentificacao; ?>"/>
            <p class="hint">Insira o seu nome.</p>
        </div>

        <div class="field">      
            <label for="login">Usuário:</label>
            <input type="text"  class="input" id="login" name="login" maxlength="25"  value ="<?= $this->funcionario->login; ?>"/>
            <p class="hint">Insira o seu nome.</p>
        </div>

        <div class="field">      
            <label for="email">E-mail:</label>
            <input type="text"  class="input" id="email" name="email" maxlength="25"  value ="<?= $this->funcionario->email; ?>"/>
            <p class="hint">Insira o seu nome.</p>
        </div>

        <input  type="submit" value="Atualizar" name="Alterar" class="button" style="width: 135px" />
        <input  type="reset" value="Limpar" name="Limpar" class="button" style="width: 135px" />

</form>
<script>
menu('13');
</script>