<?
if ( isset($this->flag)  )

         switch ($this->flag){
        case 1:
            echo "<div id='alerta'>Imagem não inserida ou o formarto do arquivo é diferente de: 'jpg', 'jpeg', 'png' ou 'gif'.</div>";
            break;
         }

?>


<ul id="globalnav">
  <li><a href="/pessoal/meusdados" >Meus Dados</a></li>
  <li><a href="/pessoal/edit" >Alterar Dados</a></li>
  <li><a href="/pessoal/imagem" class="here" >Nova Imagem</a></li>
  <li><a href="/pessoal/senha" >Alterar Senha</a></li>
</ul>
<br/>
<form id="createproject" class="rounded" action="/pessoal/imagem" method="post"  enctype = "multipart/form-data">
           <center><h3>Incluir/Alterar Foto</h3></center><br>

            <label for="foto" class="lblImgClass">Foto: </label>
            <input type="file" class="carregaImg" id="foto" name="foto"/>
            <input type="submit" class="carregaImg" id="x" value="Alterar" name="Atualizar" style="width: 135px" />
</form>
<script>
menu('13');
</script>