<ul id="globalnav">
  <li><a href="/pessoal/meusdados" >Meus Dados</a></li>
  <li><a href="/pessoal/edit" >Alterar Dados</a></li>
  <li><a href="/pessoal/imagem" class="here" >Nova Imagem</a></li>
  <li><a href="/pessoal/senha" >Alterar Senha</a></li>
</ul>

<form id="createproject" class="rounded" action="/pessoal/imagem" method="post"  enctype = "multipart/form-data">
           <center><h3>Incluir/Alterar Foto</h3></center><br>

            <label for="foto" class="lblImgClass">Foto: </label>
            <input type="file" class="carregaImg" id="foto" name="foto"/>
            <input type="submit" class="carregaImg" id="x" value="Alterar" name="Atualizar" style="width: 135px" />
</form>
<script>
menu('13');
</script>