<?
if ( isset($this->flag)  )

         switch ($this->flag){
        case 1:
            echo "<h4>Dados alterados com sucesso.</h4>";
            break;
        case 2:
            echo "<h4>Imagem alterada com sucesso</h4>";
            break;
        case 3:
            echo "<h4>Senha alterada com sucesso.</h4>";
            break;
         }

?>


<ul id="globalnav">
  <li><a href="/pessoal/meusdados" class="here" >Meus Dados</a></li>
  <li><a href="/pessoal/edit" >Alterar Dados</a></li>
  <li><a href="/pessoal/imagem" >Nova Imagem</a></li>
  <li><a href="/pessoal/senha" >Alterar Senha</a></li>
</ul>

<div id="createproject">
     <center><h3>Meus Dados</h3></center><br>
    <label for="nome" class="lblDados">Nome: </label>
    <div id="nome" class="dados">   
         <?echo $this->dados->nome;?>
    </div><br><br>
    <label for="empresa" class="lblDados">Empresa:</label>
    <div id="empresa" class="dados">   
        <?echo $this->dadosIndex->nomeEmpresa;?>
    </div><br><br>
    <label for="doc" class="lblDados">Identificação:</label>
    <div id="dov" class="dados">   
        <?echo $this->dados->documentoIdentificacao;?>
    </div><br><br>
     
    <label for="login" class="lblDados">Login:</label>
    <div id="login" class="dados">   
        <?echo $this->dados->login;?>
    </div><br><br>
    <label for="email" class="lblDados">Email:</label>
    <div id="email" class="dados">   
        <?echo $this->dados->email;?>
    </div><br><br>
    
</div>
<script>
menu('13');
</script>