<ul id="globalnav">
  <li><a href="/pessoal/meusdados" >Meus Dados</a></li>
  <li><a href="/pessoal/edit" >Alterar Dados</a></li>
  <li><a href="/pessoal/imagem" >Nova Imagem</a></li>
  <li><a href="/pessoal/senha" class="here"  >Alterar Senha</a></li>
</ul>

<?php if ( isset($this->mensagem) ): ?>

  <strong>Erro:</strong> <?= $this->mensagem ?><br><br>

 <?php endif; ?>
  
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery.validate.js"></script>
<script type="text/javascript" src="/js/jquery.maskedinput-1.3.js"></script>
  
<script type="text/javascript">
$(document).ready( function() {
	$("#createproject").validate({
		// Define as regras
		rules:{
			senhaAtual:{
				required: true, minlength: 3
			},
			senhaNova:{
				required: true, minlength: 3
			},
			senhaNova2:{
				required: true, equalTo: '#senhaNova'
			}
		}
	});
      
});
</script>  
<form id="createproject" class="rounded" action="/pessoal/senha" method="post">
<center><h3>Alterar Senha</h3></center>
<br>
<div class="field">
    <label for="senhaAtual" class="lblGeralClass">Senha atual:</label>
    <input type="password" class="input" name="senhaAtual" id="senhaAtual" />
</div>

<div class="field">
    <label for="senhaNova" class="lblGeralClass">Nova senha:</label>
    <input type="password" class="input" name="senhaNova" id="senhaNova" />
</div>
<div class="field">
    <label for="senhaNova2" class="lblGeralClass">Repita a nova senha:</label>
    <input type="password" class="input" name="senhaNova2" id="senhaNova2" />
</div>

<input type="submit" class="button" id="x" value="Atualizar" name="Atualizar" />
<input  type="reset" value="Limpar" name="Limpar" class="button" style="width: 135px" />

</form>
<script>
menu('13');
</script>