<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery.validate.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>

<script type="text/javascript">
$(document).ready( function() {
	$("#contactform").validate({
		// Define as regras
		rules:{
			name:{
				// campoNome será obrigatório (required) e terá tamanho mínimo (minLength)
				required: true, minlength: 3
			},
			email:{
				// campoEmail será obrigatório (required) e precisará ser um e-mail válido (email)
				required: true, email: true
			},
			assunto:{
				required: true
			},

                        message:{
				// campoMensagem será obrigatório (required) e terá tamanho mínimo (minLength)
				required: true, minlength: 5
			}
		}
	});
      
});
</script>

<br>
<br>

<center>
<form id="contactform" class="cmxform" method="post" action="">
<h3>Formulário de Contato</h3>
<br>
<div class="field">
	<label for="name" class="lblClass">Nome:</label>
        <input type="text" class="input" name="name" id="name"  />
</div>

<div class="field">
	<label for="email" class="lblClass">Email:</label>
  	<input type="email" class="input" name="email" id="email" type="text" />
</div>

<div class="field">
	<label for="assunto" class="lblClass">Assunto:</label>
  	<input class="input" name="assunto" id="assunto" type="text" />
</div>

<div class="field">
	<label for="message" class="lblClass">Mensagem:</label>
  	<textarea class="input" name="message" id="message"></textarea>
</div>


    <input  type="submit" value="Cadastrar" name="Cadastrar" class="button" style="width: 135px" />
    <input  type="reset" value="Limpar" name="Limpar" class="button" style="width: 135px" />

</form>
</center>
<br>
<br>

