<?php echo $this->headLink()->appendStylesheet('/css/contato.css') ?>
<br>
<br>

<center>
<form id="contactform" class="rounded" method="post" action="">
<h3>Formulário de Contato</h3>
<br>
<div class="field">
	<label for="name">Nome:</label>
  	<input type="text" class="input" name="name" id="name" />
	<p class="hint">Insira o seu nome.</p>
</div>

<div class="field">
	<label for="email">Email:</label>
  	<input type="text" class="input" name="email" id="email" />
	<p class="hint">Entre com o seu email.</p>
</div>

<div class="field">
	<label for="assunto">Assunto:</label>
  	<input type="text" class="input" name="assunto" id="assunto" />
	<p class="hint">Sobre o que você quer falar?</p>
</div>

<div class="field">
	<label for="message">Mensagem:</label>
  	<textarea class="input textarea" name="message" id="message"></textarea>
	<p class="hint">Escreva a sua mensagem, de forma clara e objetiva.</p>
</div>


<input type="submit" name="Submit"  class="button" value="Enviar" />
</center>
        </div>

<br>
<br>