<link rel="stylesheet" type="text/css" href="/css/css.css" />
<link rel="stylesheet" type="text/css" href="/css/tabela.css" />
<link rel="stylesheet" type="text/css" href="/css/tab.css" />
<link rel="stylesheet" type="text/css" href="/css/formularios.css" />

<div id="alerta">Primeiro Ascesso, Modifique sua senha.</div>

<?php if ( isset($this->mensagem) ): ?>

  <strong>Erro:</strong> <?= $this->mensagem ?><br><br>

 <?php endif; ?>

<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery.validate.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>

<script type="text/javascript">
$(document).ready( function() {
	$("#createproject").validate({
		// Define as regras
		rules:{
			senhaNova:{
				required: true, minlength: 3
			},
			senhaNova2:{
				required: true, equalTo: '#senhaNova'
			}
		}
	});
      
});

$(document).ready(function(){
        $("#alerta").dialog({
                modal : true,
                title : "Alerta do Sistema",
                resizable : false,
                draggable : false,
                buttons: {
                        Ok: function() {
                                $( this ).dialog( "close" );
                        }
                }
                        
        });
      
});

</script>  
<form  id="createproject" class="rounded" action="/auth/senha" method="post">
    <center><h3>Defina a sua senha!</h3></center><br />
    
   <input type="hidden" name="id" value="<?php echo $this->usuarioLogado->idfuncionario; ?>" />

    <div class="field">
    <label for="senhaNova" class="lblGeralClass">Nova senha:</label>
    <input type="password" class="input" id="senhaNova" name="senhaNova" />
    </div>
   
    <div class="field">
    <label for="senhaNova2" class="lblGeralClass">Repita a senha:</label>
    <input type="password" class="input" name="senhaNova2" id="senhaNova2" />
    </div>
            <input  type="submit" value="Atualizar" id="x" name="inserir" class="button" style="width: 135px" />
            <input  type="reset" value="Limpar" name="Limpar" class="button" style="width: 135px" />

    
</form>
