<script type="text/javascript">
</script>

<br>
<br>

<center>
    <div id="createproject" style="height: 360px; width: 600px; overflow-y: visible; font-size: 14px; text-align: justify; text-indent: 25px; padding: 30px 40px 0 40px; line-height: 20px">
<center><h3>Sobre o Sistema</h3></center>
<p>O SGCSFarm se propõe a transformar o complexo processo de controle de desenvolvimento de software 
em uma tarefa simplificada e acessível. Por causa de sua plataforma web e sua adaptabilidade aos padrões, 
será possível acessá-lo de qualquer lugar e a partir dos mais diversos dispositivos, tais como tablets, 
smartphones, notebooks e desktops. Proporcionando assim, maior comodidade e mobilidade aos colaboradores dos projetos.</p> <br>
<p>Com uma interface integradora, os módulos do sistema estão ao alcance dos usuários de forma simples e intuitiva, 
tornando sua utilização rápida e agradável.</p><br>
<p>O sistema está sendo desenvolvido de acordo com as normas de acessibilidade estabelecidas nos WCAG 1.0 e 2.0, 
garantindo assim sua integração com pessoas portadoras de necessidades especiais. Além disso, as normas ISO/IEC 9126, 
garantem a qualidade do produto desenvolvido sob critérios internacionais.</p>
</div>

</center>
<br>
<br>

