<?php if ( isset($this->mensagem) ): ?>

  <? echo $this->mensagem; ?>

<?php endif; ?>


<ul id="globalnav">
    <li><a href="/colaborador/index/id/<?php echo $this->projeto->current()->idprojeto; ?>">Colaboradores</a></li>   
    <li><a href="/colaborador/create/id/<?php echo $this->projeto->current()->idprojeto; ?>" class="here">Inserir Colaborador</a></li>
</ul>
<br>

<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery.validate.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){
        
	$("#createproject").validate({
		// Define as regras
		rules:{
			horas:{
				// campoNome será obrigatório (required) e terá tamanho mínimo (minLength)
				required: true
			}
                }
	});
});     

$(document).ready(function(){
        $("#alerta").dialog({
                modal : true,
                title : "Alerta do Sistema",
                resizable : false,
                buttons: {
                        Ok: function() {
                                $( this ).dialog( "close" );
                        }
                }
                        
        });
      
});
</script>

<form id="createproject" class="rounded" action="/colaborador/create" method="post">
    <center><h3>Inserir Colaborador</h3></center><br>
    
    <input type="hidden" value="<?php echo $this->projeto->current()->idprojeto;  ?>" name="id" />
    <div class="field">                    
        <label for="nome" class="lblGeralClass">Nome Projeto:</label>
        <input type="text" disabled="disabled" class="input" id="nome" name="nome" maxlength="35" value="<?php echo $this->projeto->current()->nome ?>"/>
    </div>
    <div class="field">                    
            <label for="funcionario" class="lblGeralClass">Funcionário:</label>
            <select id="funcionario" name="funcionario" class="select">
                <?php foreach ( $this->funcionario as $func) : ?>
                <option value="<?php echo $func->idfuncionario; ?>">
                    <?php echo $func->nome; ?></option>
                <?php endforeach; ?>
            </select>
    </div>
    <div class="field">                    
            <label for="nome" class="lblGeralClass">Horas por Mês:</label>
            <input type="number" id="nome" name="horas" maxlength="35" class="input" style="width: 100px" />
    </div>
    <div class="field">                    
           <label for="funcao" class="lblGeralClass">Função:</label>
            <select id="funcao" name="funcao" class="select">
                <?php foreach ( $this->funcao as $funcao) : ?>
                <option value="<?php echo $funcao->idfuncaoProjeto; ?>">
                    <?php echo $funcao->descricao; ?></option>
                <?php endforeach; ?>
            </select>
    </div>

            <input  type="submit" value="Inserir" id="x" name="inserir" class="button" style="width: 135px" />
            <input  type="reset" value="Limpar" name="Limpar" class="button" style="width: 135px" />

</form>

<script>
menu('12');
</script>
 
