
<ul id="globalnav">
    <li><a href="/colaborador/index/id/<?php echo $this->ProjGerFiliColab->current()->idprojeto; ?>">Colaboradores</a></li>   
    <li><a href="/colaborador/create/id/<?php echo $this->ProjGerFiliColab->current()->idprojeto; ?>" class="here">Inserir Colaborador</a></li>
</ul>
<br>

<form action="/colaborador/create" method="post">

        <div>
            <input type="hidden" value="<?php echo $this->ProjGerFiliColab->current()->idprojeto;  ?>" name="id" />
            
            <label for="nome">Nome Projeto:</label>
            <input type="text" disabled="disabled" id="nome" name="nome" maxlength="35" value="<?php echo $this->ProjGerFiliColab->current()->nomeProj ?>"/>
            <br><br>
                        
            <label for="funcionario">Funcionário:</label>
            <select id="funcionario" name="funcionario">
                <?php foreach ( $this->funcionario as $func) : ?>
                <option value="<?php echo $func->idfuncionario; ?>">
                    <?php echo $func->nome; ?></option>
                <?php endforeach; ?>
            </select>
            <br><br>
            
            <label for="nome">Horas por Mês:</label>
            <input type="number" id="nome" name="horas" maxlength="35" />
            <br><br>
            
           <label for="funcao">Função:</label>
            <select id="funcao" name="funcao">
                <?php foreach ( $this->funcao as $funcao) : ?>
                <option value="<?php echo $funcao->idfuncaoProjeto; ?>">
                    <?php echo $funcao->descricao; ?></option>
                <?php endforeach; ?>
            </select>
            <br><br>

            <input  type="submit" value="Cadastrar" name="Cadastrar" class="btnLogin" style="width: 135px" />
            <input  type="reset" value="Limpar" name="Limpar" class="btnLogin" style="width: 135px" />
            <br><br>
        </div>

</form>

<script>
menu('12');
</script>
 
