<?php echo $this->headLink()->appendStylesheet('/css/tabela.css'); ?>
<?
if ( isset($this->flag)  )

         switch ($this->flag){
        case 1:
            echo   "<div id='alerta'>Colaborador atualizado com sucesso!</div>";
            break;
         case 2:
            echo   "<div id='alerta'>Colaborador inserido com sucesso!</div>";
            break;
        case 4:
            echo   "<div id='alerta'>Colaborador Excluído com Sucesso</div>";
            break;
        case 5:
            echo   "<div id='alerta'>Não é possível excluir um colaborador que possua tarefas associadas a ele</div>";
            break;
         }

?>
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>

<script>

var idFuncionarioColaborador;
var idprojeto;
var idColaborador;

function confirmaDel(x,y){
    idFuncionarioColaborador = x;
    idprojeto = y;
    
    $( "#exclui" ).dialog("open");
}    

function edita(x,y){
    idFuncionarioColaborador = x;
    idprojeto = y;
    
    window.location = "/colaborador/edit/idfunc/" + idFuncionarioColaborador+ "/id/"+ idprojeto;
}

function add(x,y){
    idprojeto = x;
    idColaborador = y;
    
    window.location =  "/tarefa/create/idProj/" + idprojeto + "/idColab/" + idColaborador;
}


$(document).ready(function(){
        $("#alerta").dialog({
                modal : true,
                title : "<span class='ui-icon ui-icon-info' style='float:left; margin:1px 7px 0 0;'></span>Alerta do Sistema",
                resizable : false,
                draggable : false,
                buttons: {
                        Ok: function() {
                                $( this ).dialog( "close" );
                        }
                }
                        
        });
      
});
$(document).ready(function(){
        $("#exclui").dialog({
                autoOpen : false,
                modal : true,
                title : "<span class='ui-icon ui-icon-info' style='float:left; margin:1px 7px 0 0;'></span>Alerta do Sistema",
                resizable : false,
                draggable : false,
                buttons: {
                        Confirmar: function() {
                                window.location = "/colaborador/delete/idfunc/" + idFuncionarioColaborador + "/id/" + idprojeto;
                                $( this ).dialog( "close" );
                        },
                        Cancelar: function() {
                                $( this ).dialog( "close" );
                        }
                        
                }
                        
        });
});
$(function() {
$( ".bt .addTarefa" ).button({
            icons: {
                primary: "ui-icon-plusthick"
            },
            text: false
        })  ;
})  ;        
$(function() {        
$( ".bt .editCol" ).button({
            icons: {
                primary: "ui-icon-pencil"
            },
            text: false
        })  ;
})  ;        
$(function() {        
$( ".bt .delCol" ).button({
            icons: {
                primary: "ui-icon-trash"
            },
            text: false
        })  ;        
});
</script>

    <ul id="globalnav">
    <li><a href="/colaborador/index/id/<?php echo $this->projeto->current()->idprojeto ?>" class="here" >Colaboradores</a></li>   
    <li><a href="/colaborador/create/id/<?php echo $this->projeto->current()->idprojeto ?>">Inserir Colaborador</a></li>
    </ul>
    <br>

    <div id="createproject" >
        <center>
<table width="95%" class="tbl">
        <?
        if(count($this->paginator) == 0)
        {
        echo '<center><h3>Este projeto não possui colaboradores !</h3></center>';    
        }else{
        ?>
    
        <thead><tr><th>Nome Colaborador</th><th>Dedicação Mensal</th><th>Função</th><th>Filial</th><th>Ações</th></tr></thead>
        <tbody>
        <?
        $indice = 0;
        
        foreach ( $this->paginator as $aux) :
            
            if($indice%2){
                echo "<tr class='odd' >
                        <td width='25%'>".$aux['nomeColaborador']."</td>
                        <td width='15%' align='center'>".$aux['dedicacaoMesColaborador']."</td>
                        <td width='15%' align='center'>".$aux['funcaoColaborador']."</td>
                        <td width='15%' align='center'>".$aux['nomeFilialProj']."</td>
                        <td>
                            <div class='bt'>
                                <button class='addTarefa' onclick='add(".$aux['idprojeto'].",".$aux['idColaborador'].")'>Adicionar Tarefa</button>
                                <button class='editCol' onclick='edita(".$aux['idFuncionarioColaborador'].",".$aux['idprojeto'].")' >Editar Colaborador</button>
                                <button class='delCol'id='confirmaExclui' onclick='confirmaDel(".$aux['idFuncionarioColaborador'].",".$aux['idprojeto'].")'>Remover Colaborador do Projeto</button>
                            </div>
                        </td>                            
                    </tr>
                    </tbody>";
            } else {
                echo "<tr>
                        <td width='35%'>".$aux['nomeColaborador']."</td>
                        <td width='20%' align='center'>".$aux['dedicacaoMesColaborador']."</td>
                        <td width='17%' align='center'>".$aux['funcaoColaborador']."</td>
                        <td width='17%' align='center'>".$aux['nomeFilialProj']."</td>
                        <td>
                            <div class='bt'>
                                <button class='addTarefa' onclick='add(".$aux['idprojeto'].",".$aux['idColaborador'].")'>Adicionar Tarefa</button>
                                <button class='editCol' onclick='edita(".$aux['idFuncionarioColaborador'].",".$aux['idprojeto'].")' >Editar Colaborador</button>
                                <button class='delCol'id='confirmaExclui' onclick='confirmaDel(".$aux['idFuncionarioColaborador'].",".$aux['idprojeto'].")'>Remover Colaborador do Projeto</button>
                            </div>
                        </td>                           
                    </tr>";
            }
         $indice = $indice + 1;
          
         endforeach;
         ?>

        </tbody>
        <? } ?>
</table>
        </center>
</div>

    <div id="exclui">Tem certeza que deseja excluir?</div>

<script>
menu("12");
</script>