<?php echo $this->headLink()->appendStylesheet('/css/tabela.css'); ?>
<?
if ( isset($this->flag)  )

         switch ($this->flag){
        case 1:
            echo   "<h3>Colaborador atualizado com sucesso!</h3><br>";
            break;
         case 2:
            echo   "<h3>Colaborador inserido com sucesso!</h3><br>";
            break;
        case 4:
            echo   "<h3>Colaborador Excluído com Sucesso</h3><br>";
            break;
        case 5:
            echo   "<h3>Não é possível excluir um colaborador que possua tarefas associadas a ele</h3><br>";
            break;
         }

?>


<div id="colaboradores">
    <ul id="globalnav">
    <li><a href="/colaborador/index/id/<?php echo $this->projeto->current()->idprojeto ?>" class="here" >Colaboradores</a></li>   
    <li><a href="/colaborador/create/id/<?php echo $this->projeto->current()->idprojeto ?>">Inserir Colaborador</a></li>
    </ul>
    <br>


    <div id="createproject">
<table width="100%" class="tbl">
        <?
        if(count($this->paginator) == 0)
        {
        echo '<center><h3>Este projeto não possue colaboradores !</h3></center>';    
        }else{
        ?>
    
        <thead><tr><th>Nome Colaborador</th><th>Dedicação Mensal</th><th>Função</th><th>Filial</th><th></th><th></th></tr></thead>
        <tbody>
        <?
        $indice = 0;
        foreach ( $this->paginator as $aux ) :

            if($indice%2){
                echo "<tr class='odd' >
                        <td width='25%'>".$aux['nomeColaborador']."</td>
                        <td width='15%' align='center'>".$aux['dedicacaoMesColaborador']."</td>
                        <td width='15%' align='center'>".$aux['funcaoColaborador']."</td>
                        <td width='15%' align='center'>".$aux['nomeFilialProj']."</td>    
                        <td width='8%'><a href='/colaborador/edit/idfunc/".$aux['idFuncionarioColaborador']."/id/".$aux['idprojeto']."' class='linkLaranja' >Editar</a></td>
                        <td width='8%'><a href='/colaborador/delete/idfunc/".$aux['idFuncionarioColaborador']."/id/".$aux['idprojeto']."' class='linkLaranja' >Excluir</a></td>
                    </tr>
                    </tbody>";
            } else {
                echo "<tr>
                         <td width='25%'>".$aux['nomeColaborador']."</td>
                        <td width='15%' align='center'>".$aux['dedicacaoMesColaborador']."</td>
                        <td width='15%' align='center'>".$aux['funcaoColaborador']."</td>
                        <td width='15%' align='center'>".$aux['nomeFilialProj']."</td>    
                        <td width='8%'><a href='/colaborador/edit/idfunc/".$aux['idFuncionarioColaborador']."/id/".$aux['idprojeto']."' class='linkLaranja' >Editar</a></td>
                        <td width='8%'><a href='/colaborador/delete/idfunc/".$aux['idFuncionarioColaborador']."/id/".$aux['idprojeto']."' class='linkLaranja' >Excluir</a></td>
                    </tr>";
            }
         $indice = $indice + 1;
         endforeach; ?>

        </tbody>
        <? } ?>
</table>
  
</div>
</div>
<script>
menu('12');
</script>