<?php echo $this->headLink()->appendStylesheet('/css/formularios.css')?>

<?php
    $idColab = $this->idColab;
    $idProj = $this->projetoEncontrado->idprojeto;
    $action = "/idColab/".$idColab.'/idProj/'.$idProj.'';
?>

<script type="text/javascript">
    
$(document).ready(function(){
        
	$("#createproject").validate({
		rules:{
			descricao:{
				required: true, minlength: 10
			},
			dataInc:{
				required: true
			},
			dataFim:{
				required: true
			}
                }
	});
      
});
</script>

<form id="createproject" name="formulario_tarefa" class="rounded" method="post" action="/tarefa/create<?php echo $action; ?>">
    <center> <h3>Criar Tarefa</h3></center>
    <label for="nome" class="lblGeralClass">Para o projeto:</label>
    <div id="nome" class="dados" style="margin-left: -11px; margin-top: 1px">   
         <?php echo $this->projetoEncontrado->nome?>
    </div><br><br>
    <label for="nome" class="lblGeralClass">Para o colaborador:</label>
    <div id="nome" class="dados" style="margin-left: -11px; margin-top: 1px">   
        <?php echo $this->funcionario->nome;?>
    </div><br><br>
    <div class="field">
        <input type="hidden" name="idProj" id="idPRoj" value="<?php echo $this->projetoEncontrado->idprojeto ?>" />
        <label for="descricao" class="lblGeralClass">Descrição :</label>
        <textarea name="descricao" class="input" id="descricaoTarefa" cols="45" rows="5"></textarea>
    </div>
    <div class="field">
        <label for="dataInc" class="lblGeralClass">Data de Início:</label>
    <?php
    $data = new ZendX_JQuery_Form_Element_DatePicker("dp1",'', array(
            "defaultDate" => date('Y/m/d', time())));
    $data->setName("dataInc")
         ->setAttrib("id", "dataInc")
         ->setLabel("Data de Início da Tarefa: ")
         ->setAttrib("class", "input");
    
    echo $data;
  ?>
    </div>
    <div class="field">
        <label for="dataFim" class="lblGeralClass">Data Final:</label>

  <?php
    $data = new ZendX_JQuery_Form_Element_DatePicker("dp1",'', array(
            "defaultDate" => date('Y/m/d', time())));
    $data->setName("dataFim")
         ->setAttrib("id", "dataFim")
         ->setLabel("Data de Fim da Tarefa: ")
         ->setAttrib("class", "input");
    
    echo $data;
  ?>
    </div>
    <?php
//    $data = new ZendX_JQuery_Form_Element_DatePicker("dp1",'', array(
//            "defaultDate" => date('Y/m/d', time())));
//    $data->setName("dataEntrega")
//         ->setAttrib("id", "dataEntrega")
//         ->setLabel("Data de Entrega: ");
//    
//    echo $data;
  ?>
<!--  <label for="estadoTarefa">Estado da Tarefa :</label>-->
<!--  <select id="estadoTarefa" name="estadoTarefa">-->
    <?php // foreach ( $this->estadoTarefa as $auxEstado ) : ?>
<!--        <option value="<?php // echo $auxEstado->idestado; ?>">-->
<!--        <?php // echo $auxEstado->tipoDeEstado; ?></option>-->
    <?php // endforeach; ?>
<!--  </select>-->

        <input  type="submit" id="x" value="Criar" name="Cadastrar" class="button" style="width: 135px" />
        <input  type="reset" value="Limpar" name="Limpar" class="button" style="width: 135px" />
</form>
