<h1>Editando Tarefa</h1>

<div>Editar tarefa do projeto: <?php echo $this->projetoEncontrado->nome?>
    <br/>
    Para o colaborador: <?php echo $this->funcionario->nome;?>
    <br/>
    <br/>
</div>
<?php
    $idProj = $this->projetoEncontrado->idprojeto;
    $action = '/idProj/'.$idProj.'';
?>
<form id="formulario_tarefa" name="formulario_tarefa" method="post" action="/tarefa/edit/idTarefa/<?= $this->id; echo $action;?>">
    <label for="descricao">Descrição :</label>
    <textarea name="descricao" id="descricaoTarefa" cols="45" rows="5"><?=
        $this->tarefaEncontrada->descricao;
    ?></textarea>
    <br />
    <br />
    <?php
        $data = new ZendX_JQuery_Form_Element_DatePicker("dp1",'', array(
                "defaultDate" => date('Y/m/d', time())));
        $data->setName("dataInc")
            ->setAttrib("id", "dataInc")
            ->setLabel("Data de Início da Tarefa: ")
            ->setValue($this->tarefaEncontrada->dataInc);

        echo $data;
    ?>
    
    <br />
    <br />
   <?php
        $data = new ZendX_JQuery_Form_Element_DatePicker("dp1",'', array(
                "defaultDate" => date('Y/m/d', time())));
        $data->setName("dataFim")
            ->setAttrib("id", "dataFim")
            ->setLabel("Data de Fim da Tarefa: ")
            ->setValue($this->tarefaEncontrada->dataFim);

        echo $data;
    ?>
    <br />
    <br />
  <?php
        $data = new ZendX_JQuery_Form_Element_DatePicker("dp1",'', array(
                "defaultDate" => date('Y/m/d', time())));
        $data->setName("dataEntrega")
            ->setAttrib("id", "dataEntrega")
            ->setLabel("Data de Entrega da Tarefa: ")
            ->setValue($this->tarefaEncontrada->dataEntrega);

        echo $data;
    ?>
    <br />
    <br />
  <label for="estadoTarefa">Estado da Tarefa :</label>
  <select id="estadoTarefa" name="estadoTarefa">
   <?php foreach ( $this->estadoTarefa as $auxEstado ) : ?>
        <option <?php
                if ( $auxEstado->idestado ==  $this->tarefaEncontrada->estado_idestado)
                echo 'selected="selected"';
                ?>
                value="<?php echo $auxEstado->idestado; ?>">            
            <?php echo $auxEstado->tipoDeEstado; ?>
        </option>
    <?php endforeach; ?>
  </select>
    <br />
    <br />
  <input type="submit" name="button" id="button" class="btnLogin" value="Alterar" />
  <input type="reset" name="button2" id="button2" class="btnLogin" value="Limpar" />
</form>