<?php
    $idProj = $this->projetoEncontrado->idprojeto;
    $action = '/idProj/'.$idProj.'';
?>
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery.validate.js"></script>
<script type="text/javascript" src="/js/jquery.maskedinput-1.3.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.21.custom.min.js"></script>
<script type="text/javascript" src="/js/jquery.ui.datepicker-pt-BR.js"></script>

<script type="text/javascript">
   
$(document).ready(function(){
    
    $("#dtinicio").datepicker({});
    $("#dtfinal").datepicker({});    
});

$(document).ready(function(){
        
	$("#formulario_tarefa").validate({
		// Define as regras
		rules:{
			descricao:{
				// campoNome será obrigatório (required) e terá tamanho mínimo (minLength)
				required: true, minlength: 10
			},
			dtinicio:{
				// campoEmail será obrigatório (required) e precisará ser um e-mail válido (email)
				required: true
			},
			dtfinal:{
				required: true
			}
                }
	});
      
});
</script>

<ul id="globalnav">
  <li><a href="/projeto/index" >Projetos que colaboro</a></li>
  <li><a href="/projeto/gerencio">Projetos que gerencio</a></li>
  <li><a href="/projeto/detalhesgerente/idProj/<?php echo $this->projetoEncontrado->idprojeto; ?>">Detalhes</a></li>
  <li><a href="/tarefa/prepara/idProj/<?php echo $this->projetoEncontrado->idprojeto;  ?>">Tarefas</a></li>
  <li><a href="#" class="here">Editar Tarefa</a></li>
  
</ul>
<br/>
<form id="createproject" class="rounded" name="formulario_tarefa" method="post" action="/tarefa/edit/idTarefa/<?= $this->id; echo $action;?>">
    <center><h3>Editar Tarefa</h3></center>

<center><div>Editar tarefa do projeto: <?php echo $this->projetoEncontrado->nome?>
    <br/>
    Para o colaborador: <?php echo $this->funcionario->nome;?>    <br/>    <br/>
</div></center>
    <div class="field">
    <label for="descricao" class="lblGeralClass">Descrição :</label>
        <textarea name="descricao" class="input" id="descricao" cols="45" rows="5"><?=
            $this->tarefaEncontrada->descricao;?>
        </textarea>
    </div>
    
    <div class="field">      
            <label for="dtinicio" class="lblGeralClass">Data de início da tarefa:</label>
            <input type="text" id="dtinicio" class="input" name="dataInc" value="<?= $this->tarefaEncontrada->dataInc; ?>" />
        </div>
    
   <div class="field">      
            <label for="dtfinal" class="lblGeralClass">Data de entrega da tarefa:</label>
            <input type="text" id="dtfinal" class="input" name="dataFim" value="<?= $this->tarefaEncontrada->dataFim; ?>" />
        </div>
    
    <div class="field">
        <label for="estadoTarefa" class="lblGeralClass">Estado da Tarefa :</label>
        <select id="estadoTarefa" class="select" name="estadoTarefa">
        <?php foreach ( $this->estadoTarefa as $auxEstado ) : ?>
        <option <?php
                if ( $auxEstado->idestado ==  $this->tarefaEncontrada->estado_idestado)
                echo 'selected="selected"';
                ?>
                value="<?php echo $auxEstado->idestado; ?>">            
            <?php echo $auxEstado->tipoDeEstado; ?>
        </option>
    <?php endforeach; ?>
  </select>
    </div>
    <div>  
        <input  type="submit" id="x" value="Alterar" name="Cadastrar" class="button" style="width: 135px" />
        <input  type="reset" value="Limpar" name="Limpar" class="button" style="width: 135px" />
    </div>
</form>
