<?php echo $this->headLink()->appendStylesheet('/css/tabela.css') ?>
<br/>

<center><h3>Tarefas do <?php echo $this->projEncontrado->nome;?></h3></center>

<table width="100%" class="tbl">
    <thead><tr>
        <th>Colaborador Respons&aacute;vel</th>
        <th>Descri&ccedil;&atilde;o da Tarefa</th>
        <th>Data de In&iacute;cio</th>
        <th>Data de Fim</th>
        <th>Data da Entrega</th>
        <th>Estado</th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php
    $indice = 0;
    foreach ( $this->paginator as $auxTarColabProj ) :
        if($indice%2){
        echo "<tr  class='odd'>
                <td align='center'>".$auxTarColabProj->nomeFunc."</td>
                <td align='center'>".$auxTarColabProj->descricaoTarefa."</td>  
                <td align='center'>".$auxTarColabProj->dataInc."</td>
                <td align='center'>".$auxTarColabProj->dataFim."</td>
                <td align='center'>".$auxTarColabProj->dataEntrega."</td>
                ";
        foreach ( $this->listaEstado as $auxEstado ) :
            if($auxEstado->idestado == $auxTarColabProj->estado_idestado){
                echo "<td align='center'>".$auxEstado->tipoDeEstado."</td>";
            }
        endforeach;
        echo "<td align='center'>
             <a 
             href='/tarefa/edit/idTarefa/".$auxTarColabProj->idtarefa."/idColab/".$auxTarColabProj->idColab."/idProj/".$this->projEncontrado->idprojeto."' >
                 Editar
             </a></td>
             </tr></tbody>";
        }else{
        echo "<tr>
                <td align='center'>".$auxTarColabProj->nomeFunc."</td>
                <td align='center'>".$auxTarColabProj->descricaoTarefa."</td>  
                <td align='center'>".$auxTarColabProj->dataInc."</td>
                <td align='center'>".$auxTarColabProj->dataFim."</td>
                <td align='center'>".$auxTarColabProj->dataEntrega."</td>
                ";
        foreach ( $this->listaEstado as $auxEstado ) :
            if($auxEstado->idestado == $auxTarColabProj->estado_idestado){
                echo "<td align='center'>".$auxEstado->tipoDeEstado."</td>";
            }
        endforeach;
        echo "<td align='center'>
             <a 
             href='/tarefa/edit/idTarefa/".$auxTarColabProj->idtarefa."/idColab/".$auxTarColabProj->idColab."/idProj/".$this->projEncontrado->idprojeto."' >
                 Editar
             </a></td></tr></tbody>";
        }
        
    $indice = $indice + 1;
    endforeach;
    ?>
        </tbody>
</table>
<div>
    <?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?>
</div>

<script>
menu('13');
</script>