<?php echo $this->headLink()->appendStylesheet('/css/tabela.css')
                            ->appendStylesheet('/css/tarefas_css.css')
                            ->appendStylesheet('/css/formularios.css');
?>
<?php
if ( isset($this->flag)  )
         switch ($this->flag){
        case 1:
            echo   "<div id='alerta'>Tarefa cadastrada com sucesso!</div>";
            break;
        case 2:
            echo   "<div id='alerta'>Tarefa atualizada com sucesso!</div>";
            break;
        case 3:
            echo "<div id='alerta'>Tarefa excluída com sucesso!</div>";
            break;
        case 4:
            echo "<div id='alerta'>Não foi possivel Excluir ou Alterar a tarefa. Verifique:
                <br> - Se você não alterou algum dado.
                <br> - Se a tarefa já foi excluída.</div>";
            break;
         }
?>

<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $("#alerta").dialog({
                modal : true,
                title : "<span class='ui-icon ui-icon-info' style='float:left; margin:1px 7px 0 0;'></span>Alerta do Sistema",
                resizable : false,
                draggable : false,
                buttons: {
                        Ok: function() {
                                $( this ).dialog( "close" );
                        }
                }
                        
        });
      
});
</script>

<ul id="globalnav">
  <li><a href="/projeto/index" >Projetos que colaboro</a></li>
  <li><a href="/projeto/gerencio">Projetos que gerencio</a></li>
  <li><a href="/projeto/detalhesgerente/idProj/<?php echo $this->projEncontrado->idprojeto; ?>">Detalhes</a></li>
  <li><a href="#" class="here">Tarefas</a></li>
  
</ul>
<br/>
<div id="detalhes_tarefas">
<center>
<div id="perara_tarefa_add_colab">
    <h3>Adicionar Tarefa</h3>
    <form id="escolheColab" name="escolheColab" method="post" action="/tarefa/prepara">
        <br />

        <b>Nome do Projeto : <?php echo $this->projEncontrado->nome;?></b>
        <input type="hidden" value="<?php echo $this->projEncontrado->idprojeto ?>" name="idProj" />
        <br />
        <br />
        <b><label for="listColab" class="lblGeralClass" style="margin-right: -75px;">Escolha um colaborador:</label></b>
            <select id="listColab" name="listColab" class="select">
                <option value=""> - - Escolha um Colaborador - - </option>

            <?php foreach ( $this->listaColaboradores as $auxColab ) : ?>
                <?php foreach ( $this->listaFuncionarios as $auxFunc ) : ?>
                    <?php if($auxFunc->idfuncionario == $auxColab->funcionario_idfuncionario){?>
                        <option value="<?php echo $auxColab->idcolaboradores; ?>">
                        <?php echo $auxFunc->nome; ?></option>
                    <?php }?>
                <?php endforeach; ?>
            <?php endforeach; ?>   
        </select>
        <input type="submit" class="carregaImg" value="Ok" name="button" style="width: 100px; float:right; margin-right: 200px" />

    </form>
</div>
</center>
<br/>
<center>
<div id="conteudo_tarefas">
    <center>
        <br/>
        <h2>Todas as Tarefas</h2>
        <br/>
        <?php if(count($this->paginator) == 0){?>
        <br/>
        <center><h3>Este Projeto ainda não tem tarefas</h3></center>
        <?php } ?>
    <?php foreach ( $this->paginator as $auxTarColabProj ) : ?>
        <div class="tarefas">
            Colaborador Respons&aacute;vel: <?php echo $auxTarColabProj->nomeFunc; ?><br/>
            Descri&ccedil;&atilde;o da Tarefa: <?php echo $auxTarColabProj->descricaoTarefa; ?><br/>
            Data de In&iacute;cio: <?php echo $auxTarColabProj->dataInc;?><br/>
            Previsao da Entrega: <?php echo $auxTarColabProj->dataFim;?><br/>
            <?php foreach ( $this->listaEstado as $auxEstado ) :
                if($auxEstado->idestado == $auxTarColabProj->estado_idestado){
                    if($auxEstado->tipoDeEstado == "Concluido"){
                        echo "<span style='color:blue; 
                            text-transform:uppercase;'>Estado: <b>".$auxEstado->tipoDeEstado."</b><br/>";
                        echo "Data da entrega:<b>".$auxTarColabProj->dataEntrega."</b></span><br/>";
                    }else{
                    echo "Estado: ".$auxEstado->tipoDeEstado."<br/>";
                }
                    
                }
            endforeach; ?>
            <br/>
            <?php 
                echo "<a title='Editar Tarefa' href='/tarefa/edit/idTarefa/".$auxTarColabProj->idtarefa."/idColab/".$auxTarColabProj->idColab."/idProj/".$this->projEncontrado->idprojeto."' >
                          <img src='/images/b_edit.png' width='20px' height='20px' alt='editar tarefa'/></a>
                      &nbsp;&nbsp;
                      <a title='Excluir Tarefa' class='excluir' href='/tarefa/delete/idTarefa/".$auxTarColabProj->idtarefa."/idColab/".$auxTarColabProj->idColab."/idProj/".$this->projEncontrado->idprojeto."' >
                        <img src='/images/b_drop.png' width='20px' height='20px' alt='excluir tarefa'/></a>"
            ?>
        </div>
    <?php endforeach; ?>
    </center>
</div>
</center>
<br/>
<center>
<div>
    <?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?>
</div>
</center>
<br/>
</div>


<!--
<center><h3>Tarefas do <?php echo $this->projEncontrado->nome;?></h3></center>

<table width="100%" class="tbl">
    <thead><tr>
        <th>Colaborador Respons&aacute;vel</th>
        <th>Descri&ccedil;&atilde;o da Tarefa</th>
        <th>Data de In&iacute;cio</th>
        <th>Data de Fim</th>
        <th>Data da Entrega</th>
        <th>Estado</th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>-->
    <?php
//    $indice = 0;
//    foreach ( $this->paginator as $auxTarColabProj ) :
//        if($indice%2){
//        echo "<tr  class='odd'>
//                <td align='center'>".$auxTarColabProj->nomeFunc."</td>
//                <td align='center'>".$auxTarColabProj->descricaoTarefa."</td>  
//                <td align='center'>".$auxTarColabProj->dataInc."</td>
//                <td align='center'>".$auxTarColabProj->dataFim."</td>
//                <td align='center'>".$auxTarColabProj->dataEntrega."</td>
//                ";
//        foreach ( $this->listaEstado as $auxEstado ) :
//            if($auxEstado->idestado == $auxTarColabProj->estado_idestado){
//                echo "<td align='center'>".$auxEstado->tipoDeEstado."</td>";
//            }
//        endforeach;
//        echo "<td align='center'>
//             <a 
//             href='/tarefa/edit/idTarefa/".$auxTarColabProj->idtarefa."/idColab/".$auxTarColabProj->idColab."/idProj/".$this->projEncontrado->idprojeto."' >
//                 Editar
//             </a></td>
//             <td align='center'>
//             <a class='excluir' 
//             href='/tarefa/delete/idTarefa/".$auxTarColabProj->idtarefa."/idColab/".$auxTarColabProj->idColab."/idProj/".$this->projEncontrado->idprojeto."' >
//                Excluir
//             </a></td></tr></tbody>";
//        }else{
//        echo "<tr>
//                <td align='center'>".$auxTarColabProj->nomeFunc."</td>
//                <td align='center'>".$auxTarColabProj->descricaoTarefa."</td>  
//                <td align='center'>".$auxTarColabProj->dataInc."</td>
//                <td align='center'>".$auxTarColabProj->dataFim."</td>
//                <td align='center'>".$auxTarColabProj->dataEntrega."</td>
//                ";
//        foreach ( $this->listaEstado as $auxEstado ) :
//            if($auxEstado->idestado == $auxTarColabProj->estado_idestado){
//                echo "<td align='center'>".$auxEstado->tipoDeEstado."</td>";
//            }
//        endforeach;
//        echo "<td align='center'>
//             <a 
//             href='/tarefa/edit/idTarefa/".$auxTarColabProj->idtarefa."/idColab/".$auxTarColabProj->idColab."/idProj/".$this->projEncontrado->idprojeto."' >
//                 Editar
//             </a></td>
//             <td align='center'>
//             <a class='excluir' 
//             href='/tarefa/delete/idTarefa/".$auxTarColabProj->idtarefa."/idColab/".$auxTarColabProj->idColab."/idProj/".$this->projEncontrado->idprojeto."' >
//                Excluir
//             </a></td></tr></tbody>";
//        }
//        
//    $indice = $indice + 1;
//    endforeach;
    ?>
<!--        </tbody>
</table>-->
