
<?php echo $this->headLink()->appendStylesheet('/css/tabela.css') ?>
<?php echo $this->headLink()->appendStylesheet('/css/tab.css') ?>

<ul id="globalnav">
  <li><a href="/funcionario/index">Funcionarios</a></li>
  <li><a href="/funcionario/create" class="here">Cadastrar Usuario</a></li>
  <li><a href="/projeto/adminfilial">Projetos</a></li>
  <li><a href="/projeto/create" >Criar Projeto</a></li>
</ul>

<?
if ( isset($this->flag)  )

    switch ($this->flag){
        case 1:
            echo   "<h3>Cadastro não realizado: Documento de indentificação já cadastrado.</h3>";
            break;
        case 2:
            echo   "<h3>Cadastro não realizado: O usuário escolhido já existe. </h3>";
            break;
         }
?>

<form action="/funcionario/create" method="post">

        <div>

            <label for="nome">Nome:</label>
            <input type="text" id="nome" name="nome" maxlength="35"/>
            <br><br>

            <label for="doc">Identidade:</label>
            <input type="text" id="doc" name="doc" maxlength="25"/>
            <br><br>

            <label for="login">Usuário:</label>
            <input type="text" id="login" name="login" maxlength="25"/>
            <br><br>

            <label for="email">E-mail:</label>
            <input type="text" id="email" name="email" maxlength="25"/>
            <br><br>

            <input  type="submit" value="Cadastrar" name="Cadastrar" class="btnLogin" style="width: 135px" />
            <br><br>
        </div>

</form>
<script>
menu('17');
</script>