
<ul id="globalnav">
  <li><a href="/funcionario/indexemp" >Funcionarios</a></li>
  <li><a href="#" class="here">Cadastrar Reponsável</a></li>
  <li><a href="/filial" >Filiais</a></li>
  <li><a href="/filial/create" >Cadastrar Filial</a></li>
  <li><a href="/projeto/admingeral">Projetos da Empresa</a></li>
</ul>

<?
if ( isset($this->flag)  )

    switch ($this->flag){
        case 1:
            echo   "<div id='alerta'>Cadastro não realizado: Documento de indentificação já cadastrado.</div>";
            break;
        case 2:
            echo   "<div id='alerta'>Cadastro não realizado: O usuário escolhido já existe. </div>";
            break;
         }
?>
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery.validate.js"></script>
<script type="text/javascript" src="/js/jquery.maskedinput-1.3.js"></script>

<script type="text/javascript">
$(document).ready(function(){

	$("#createproject").validate({
		// Define as regras
		rules:{
			nome:{
				required: true, minlength: 3
			},
			doc:{
				required: true
			},
			login:{
				required: true, minlength: 3
			},
			email:{
				required: true, email: true
			}
                }
	});

});
</script>

<form id="createproject" class="rounded" action="/funcionario/createemp" method="post">
    <center><h3>Novo Responsável</h3></center><br>
        <div class="field">
            <label for="name" class="lblGeralClass">Nome:</label>
            <input type="text" class="input" id="name" name="nome" maxlength="35"/>
        </div>
        <div class="field">
            <label for="doc" class="lblGeralClass">Identidade:</label>
            <input type="text" class="input" id="doc" name="doc" maxlength="25"/>
        </div>
        <div class="field">
            <label for="login" class="lblGeralClass">Usuário:</label>
            <input type="text" class="input" id="login" name="login" maxlength="25"/>
        </div>
        <div class="field">
            <label for="email" class="lblGeralClass">E-mail:</label>
            <input type="text" class="input" id="email" name="email" maxlength="25"/>
        </div>
        <br>

        <input  type="submit" id="x" value="Cadastrar" name="Cadastrar" class="button" style="width: 135px" />
        <input  type="reset" value="Limpar" name="Limpar" class="button" style="width: 135px" />

</form>

<script>
menu('17');
</script>