
<?php echo $this->headLink()->appendStylesheet('/css/tabela.css') ?>
<?php echo $this->headLink()->appendStylesheet('/css/tab.css') ?>

<ul id="globalnav">
  <li><a href="/funcionario/meusdados" >Meus Dados</a></li>
  <li><a href="/funcionario/create" class="here">Cadastrar Usuario</a></li>
  <li><a href="/funcionario/index" >Funcionarios</a></li>
</ul>


<form action="/funcionario/create" method="post">

        <div>
            <br><br>
            <label for="filial">Filial:</label>
            <select id="filial" name="idFilial">
                <?php foreach ( $this->filial as $filial ) : ?>
                <option value="<?php echo $filial->idempresaFilial; ?>">
                    <?php echo $filial->nome; ?></option>
                <?php endforeach; ?>
            </select>
            <br><br>

            <label for="nome">Nome:</label>
            <input type="text" id="nome" name="nome" maxlength="35"/>
            <br><br>

            <label for="doc">Identidade:</label>
            <input type="text" id="doc" name="doc" maxlength="25"/>
            <br><br>

            <label for="login">Usuário:</label>
            <input type="text" id="login" name="login" maxlength="25"/>
            <br><br>

            <label for="email">E-mail:</label>
            <input type="text" id="email" name="email" maxlength="25"/>
            <br><br>

            <input  type="submit" value="Cadastrar" name="Cadastrar" class="btnLogin" style="width: 135px" />
            <br><br>
        </div>

</form>
<script>
menu('13');
</script>