<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery.validate.js"></script>
<script type="text/javascript" src="/js/jquery.maskedinput-1.3.js"></script>
<script type="text/javascript">

$(document).ready(function(){

	$("#createproject").validate({
		// Define as regras
		rules:{
			nome:{
				required: true, minlength: 3
			},
			email:{
				required: true, email: true
			}
                }
	});

});
</script>

<?
if ( isset($this->flag)  )

         switch ($this->flag){
        case 1:
            echo   "<div id='alerta'>Não é possivel tranferir o funcionario, verifique se o funcionario em questão<br>
                    esta incluido em algum projeto na sua filial de origem</div>";
            break;
         }

?>


<ul id="globalnav">
  <li><a href="/funcionario/indexemp" >Funcionarios</a></li>
  <li><a href="/funcionario/createemp">Cadastrar Reponsável</a></li>
  <li><a href="/filial" >Filiais</a></li>
   <li><a href="/filial/create" >Cadastrar Filial</a></li>
   <li><a href="/projeto/admingeral">Projetos da Empresa</a></li>
  <li><a href="#" class="here">Editar / Transferir Funcionário</a></li>
</ul>
<br/>

<form id="createproject" class="rounded" action="/funcionario/editemp" method="post">
    <center><h3>Alterar Dados de Funcionário</h3></center><br>
            <input type="hidden" value="<?=$this->funcionario->idfuncionario;?>" name="id" />
            <input type="hidden" value="<?=$this->funcionario->empresaFilial_idempresaFilial;?>" name="id_filial" />
         <div class="field">
            <label for="filial" class="lblGeralClass" >Filial:</label>
            <select id="filial" name="idFilial" class="select" >
             <option  value="0">Responsável Filial</option >
            <?php foreach ( $this->filial as $filial ) : ?>
                <option <?php
                        if ( $filial->idempresaFilial == $this->funcionario->empresaFilial_idempresaFilial )
                        echo 'selected="selected"';
                        ?>
                        value="<?php echo $filial->idempresaFilial; ?>">

                    <?php echo $filial->nome; ?>
                </option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="field">
            <label for="nome" class="lblGeralClass">Nome:</label>
            <input type="text" class="input" id="nome" name="nome" maxlength="35" value ="<?= $this->funcionario->nome; ?>"/>
        </div>
        <div class="field">
            <label for="doc" class="lblGeralClass">Identidade:</label>
            <input type="text" class="input" id="doc" name="doc" disabled="disabled" maxlength="25" value ="<?= $this->funcionario->documentoIdentificacao; ?>"/>
        </div>
        <div class="field">
            <label for="login" class="lblGeralClass">Usuário:</label>
            <input type="text" class="input" id="login" name="login" disabled="disabled" maxlength="25"  value ="<?= $this->funcionario->login; ?>"/>
        </div>
        <div class="field">
            <label for="email" class="lblGeralClass">E-mail:</label>
            <input type="text" class="input" id="email" name="email" maxlength="25"  value ="<?= $this->funcionario->email; ?>"/>
        </div>

        <input  type="submit" id="x" value="Atualizar" name="Cadastrar" class="button" style="width: 135px" />
        <input  type="reset" value="Limpar" name="Limpar" class="button" style="width: 135px" />
</form>
<script>
menu('17');
</script>

