<ul id="globalnav">
  <li><a href="/funcionario/index">Funcionarios</a></li>
  <li><a href="/funcionario/create">Cadastrar Funcionário</a></li>
  <li><a href="/projeto/adminfilial">Projetos</a></li>
  <li><a href="/projeto/create" >Criar Projeto</a></li>
   <li><a href="#" class="here">Editar Funcionarios</a></li>
</ul>
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery.validate.js"></script>
<script type="text/javascript" src="/js/jquery.maskedinput-1.3.js"></script>
<script type="text/javascript">
$(document).ready(function(){
        
	$("#createproject").validate({
		// Define as regras
		rules:{
			nome:{
				required: true, minlength: 3
			},
			email:{
				required: true, email: true
			}
                }
	});
      
});
</script>
<form id="createproject" class="rounded" action="/funcionario/edit" method="post">
    <center><h3>Alterar Dados de Funcionário</h3></center><br>
            <input type="hidden" value="<?=$this->funcionario->idfuncionario;?>" name="id" />
        <div class="field">            
            <label for="nome" class="lblGeralClass">Nome:</label>
            <input type="text" class="input" id="nome" name="nome" maxlength="35" value ="<?= $this->funcionario->nome; ?>"/>
        </div>    
        <div class="field">            
            <label for="doc" class="lblGeralClass">Identidade:</label>
            <input type="text" class="input" id="doc" name="doc" disabled="disabled" maxlength="25" value ="<?= $this->funcionario->documentoIdentificacao; ?>"/>
        </div>    
        <div class="field">            
            <label for="login" class="lblGeralClass">Usuário:</label>
            <input type="text" class="input" id="login" name="login" disabled="disabled" maxlength="25"  value ="<?= $this->funcionario->login; ?>"/>
        </div>    
        <div class="field">            
            <label for="email" class="lblGeralClass">E-mail:</label>
            <input type="text" class="input" id="email" name="email" maxlength="25"  value ="<?= $this->funcionario->email; ?>"/>
        </div>    

        <input  type="submit" id="x" value="Atualizar" name="Cadastrar" class="button" style="width: 135px" />
        <input  type="reset" value="Limpar" name="Limpar" class="button" style="width: 135px" />

</form>
<script>
menu('17');
</script>