<ul id="globalnav">
  <li><a href="/funcionario/index">Funcionarios</a></li>
  <li><a href="/funcionario/create">Cadastrar Usuario</a></li>
  <li><a href="/projeto/adminfilial">Projetos</a></li>
  <li><a href="/projeto/create" >Criar Projeto</a></li>
   <li><a href="#" class="here">Editar Funcionarios</a></li>
</ul>

<form action="/funcionario/edit" method="post">
        <div>

            <input type="hidden" value="<?=$this->funcionario->idfuncionario;?>" name="id" />
            
            <label for="nome">Nome:</label>
            <input type="text" id="nome" name="nome" maxlength="35" value ="<?= $this->funcionario->nome; ?>"/>
            <br><br>

            <label for="doc">Identidade:</label>
            <input type="text" id="doc" name="doc" disabled="disabled" maxlength="25" value ="<?= $this->funcionario->documentoIdentificacao; ?>"/>
            <br><br>

            <label for="login">Usuário:</label>
            <input type="text" id="login" name="login" disabled="disabled" maxlength="25"  value ="<?= $this->funcionario->login; ?>"/>
            <br><br>

            <label for="email">E-mail:</label>
            <input type="text" id="email" name="email" maxlength="25"  value ="<?= $this->funcionario->email; ?>"/>
            <br><br>

            <input  type="submit" value="atualizar" name="Atualizar" />
            <br><br>
        </div>

</form>
<script>
menu('16');
</script>