<ul id="globalnav">
  <li><a href="#" class="here">Funcionarios</a></li>
  <li><a href="/funcionario/createemp">Cadastrar Reponsável</a></li>
  <li><a href="/filial" >Filiais</a></li>
  <li><a href="/filial/create" >Cadastrar Filial</a></li>
  <li><a href="/projeto/admingeral">Projetos da Empresa</a></li>
</ul>

<?
if ( isset($this->flag)  )

         switch ($this->flag){
        case 1:
            echo   "<h3>Funcionario cadastrado com sucesso!</h3><br>";
            break;
        case 2:
            echo   "<h3>Funcionario atualizado com sucesso!</h3><br>";
            break;
        case 3:
            echo   "<h3>Funcionario excluído com sucesso!</h3><br>";
            break;
        case 4:
            echo "<h4>Não foi possivel transferir o funcionario, verifique:<br> Se o funcionario é responsavel por alguma filial;<br>
                Se o funcionario é colaborador em algum projeto;<br>Se o funcionario é gerente de algum projeto;<br>
                Caso alguma dessas opções seja positiva, as modifique e volte a tentar a transferência.</h4><br>";
            break;
        case 5:
             echo   "<h3>Funcionario transferido com sucesso!</h3><br>";
            break;
         }

?>


 <div id="createproject" >
<center>
<table width="95%" class="tbl">

        <thead><tr><th>Nome</th><th>Identidade</th><th>Email</th><th></th><th></th></tr></thead>
        <tbody>
        <?
        $indice = 0;
        foreach ( $this->paginator as $aux ) :

            if($indice%2){
                echo "<tr class='odd' >
                        <td width='33%'>".$aux['nome']."</td>
                        <td width='16%'>".$aux['documentoIdentificacao']."</td>
                        <td width='33%'>".$aux['email']."</td>
                        <td width='8%'><a href='/funcionario/edit/id/".$aux['idfuncionario']."' class='linkLaranja' >Editar</a></td>
                        <td width='8%'><a href='/funcionario/delete/tipo/2/id/".$aux['idfuncionario']."' class='linkLaranja' >Excluir</a></td>
                    </tr>
                    </tbody>";
            } else {
                echo "<tr>
                        <td width='33%'>".$aux['nome']."</td>
                        <td width='16%'>".$aux['documentoIdentificacao']."</td>
                        <td width='33%'>".$aux['email']."</td>
                        <td width='8%'><a href='/funcionario/editemp/id/".$aux['idfuncionario']."' class='linkLaranja' >Editar</a></td>
                        <td width='8%'><a href='/funcionario/delete/id/".$aux['idfuncionario']."' class='linkLaranja' >Excluir</a></td>
                    </tr>";
            }
         $indice = $indice + 1;
         endforeach; ?>
            </tbody>
</table>

</center>
<br>

<div>
    <center><?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?></center>
</div>
</div>
<script>
menu('13');
</script>