<?
if ( isset($this->flag)  )

         switch ($this->flag){
        case 1:
            echo   "<h3>Funcionario cadastrado com sucesso!</h3><br>";
            break;
        case 2:
            echo   "<h3>Funcionario atualizado com sucesso!</h3><br>";
            break;
        case 3:
            echo "<h3>Funcionario excluído com sucesso!</h3><br>";
            break;
        case 4:
            echo "<h4>Não foi possivel deletar o funcionario, verifique:<br> Se o funcionario é responsavel por alguma filial;<br>
                Se o funcionario é colaborador em algum projeto;<br>Se o funcionario é gerente de algum projeto;<br>
                Caso alguma dessas opções seja positiva, as modifique e volte a tentar a escluxão.</h4><br>";
            break;
         }
?>

<?php echo $this->headLink()->appendStylesheet('/css/tabela.css') ?>

<a href="/funcionario/create">Cadastrar Usuario</a><br><br>
<center>
<table width="100%" class="tbl">

        <thead><tr><th>Nome</th><th>Identidade</th><th>Email</th><th></th><th></th></tr></thead>
        <?
        $indice = 0;
        foreach ( $this->paginator as $aux ) :
        
            if($indice%2){
                echo "<tbody>
                    <tr class='odd' >
                        <td width='33%'>".$aux['nome']."</td>
                        <td width='16%'>".$aux['documentoIdentificacao']."</td>
                        <td width='33%'>".$aux['email']."</td>
                        <td width='8%'><a href='/funcionario/edit/id/".$aux['idfuncionario']."' class='linkLaranja' >Editar</a></td>
                        <td width='8%'><a href='/funcionario/delete/id/".$aux['idfuncionario']."' class='linkLaranja' >Excluir</a></td>
                    </tr>
                    </tbody>";
            } else {
                echo "<tbody>
                    <tr>
                        <td width='33%'>".$aux['nome']."</td>
                        <td width='16%'>".$aux['documentoIdentificacao']."</td>
                        <td width='33%'>".$aux['email']."</td>
                        <td width='8%'><a href='/funcionario/edit/id/".$aux['idfuncionario']."' class='linkLaranja' >Editar</a></td>
                        <td width='8%'><a href='/funcionario/delete/id/".$aux['idfuncionario']."' class='linkLaranja' >Excluir</a></td>
                    </tr>
                    </tbody>";
            }
         $indice = $indice + 1;   
         endforeach; ?>
</table>    
    
</center>
<br>
<div>
    <center><?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?></center>
</div>
<script>
menu('12');
</script>

