<?
if ( isset($this->flag)  )

         switch ($this->flag){
        case 1:
            echo   "<h3>Funcionario cadastrado com sucesso!</h3><br>";
            break;
        case 2:
            echo   "<h3>Funcionario atualizado com sucesso!</h3><br>";
            break;
        case 3:
            echo "<h3>Funcionario excluído com sucesso!</h3><br>";
            break;
        case 4:
            echo "<h4>Não foi possivel deletar o funcionario, verifique:<br> Se o funcionario é responsavel por alguma filial;<br>
                Se o funcionario é colaborador em algum projeto;<br>Se o funcionario é gerente de algum projeto;<br>
                Caso alguma dessas opções seja positiva, as modifique e volte a tentar a escluxão.</h4><br>";
            break;
         }
?>

<?php echo $this->headLink()->appendStylesheet('/css/tabela.css') ?>
<?php echo $this->headLink()->appendStylesheet('/css/tab-view.css') ?>
<?php echo $this->headScript()->appendFile("/js/ajax.js"); ?>
<?php echo $this->headScript()->appendFile("/js/tab-view.js"); ?>

<a href="/funcionario/create">Cadastrar Usuario</a><br><br>
<center>
<table width="100%" class="tbl">

        <thead><tr><th>Nome</th><th>Identidade</th><th>Email</th><th></th><th></th></tr></thead>
        <tbody>
        <?
        $indice = 0;
        foreach ( $this->paginator as $aux ) :
        
            if($indice%2){
                echo "<tr class='odd' >
                        <td width='33%'>".$aux['nome']."</td>
                        <td width='16%'>".$aux['documentoIdentificacao']."</td>
                        <td width='33%'>".$aux['email']."</td>
                        <td width='8%'><a href='/funcionario/edit/id/".$aux['idfuncionario']."' class='linkLaranja' >Editar</a></td>
                        <td width='8%'><a href='/funcionario/delete/id/".$aux['idfuncionario']."' class='linkLaranja' >Excluir</a></td>
                    </tr>
                    </tbody>";
            } else {
                echo "<tr>
                        <td width='33%'>".$aux['nome']."</td>
                        <td width='16%'>".$aux['documentoIdentificacao']."</td>
                        <td width='33%'>".$aux['email']."</td>
                        <td width='8%'><a href='/funcionario/edit/id/".$aux['idfuncionario']."' class='linkLaranja' >Editar</a></td>
                        <td width='8%'><a href='/funcionario/delete/id/".$aux['idfuncionario']."' class='linkLaranja' >Excluir</a></td>
                    </tr>";
            }
         $indice = $indice + 1;   
         endforeach; ?>
            </tbody>
</table>    
    
</center>
<br>

<div>
    <center><?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?></center>
</div>



<div id="abasUsuario">
	<div class="dhtmlgoodies_aTab">
        </div>
</div>  

<script type="text/javascript">

menu('12');

//initTabs('mainContainerID','tabTitles','activeTab',width,height,closeButtonArray,additionalTab)
initTabs('abasUsuario',Array('Usuários'),0,'100%',200,Array(false));

//createNewTab(parentId,tabTitle,tabContent,tabContentUrl,closeButton)
createNewTab('abasUsuario','Cadastrar Usuário','','create',false);

//showTab('mainContainerID', indice)
showTab('abasUsuario','0');

</script>

