<ul id="globalnav">
  <li><a href="#" class="here">Funcionarios</a></li>
  <li><a href="/funcionario/createemp">Cadastrar Reponsável</a></li>
  <li><a href="/filial" >Filiais</a></li>
  <li><a href="/filial/create" >Cadastrar Filial</a></li>
  <li><a href="/projeto/admingeral">Projetos da Empresa</a></li>
</ul>
<br/>
<?
if ( isset($this->flag)  )
         switch ($this->flag){
        case 1:
            echo   "<div id='alerta'>Funcionario cadastrado com sucesso!</div>";
            break;
        case 2:
            echo   "<div id='alerta'>Funcionario atualizado com sucesso!</div>";
            break;
        case 3:
            echo   "<div id='alerta'>Funcionario excluído com sucesso!</div>";
            break;
        case 4:
            echo "<div id='alerta'>Não foi possivel transferir o funcionario, verifique:<br> Se o funcionario é responsavel por alguma filial;<br>
                Se o funcionario é colaborador em algum projeto;<br>Se o funcionario é gerente de algum projeto;<br>
                Caso alguma dessas opções seja positiva, as modifique e volte a tentar a transferência.</div>";
            break;
        case 5:
             echo   "<div id='alerta'>Funcionario transferido com sucesso!</div>";
            break;
         };
?>

<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>

<script type="text/javascript">

var idFuncionario;

function edita(x){
    idFuncionario = x;
    
    window.location = "/funcionario/editemp/id/" + idFuncionario;
    
}

function confirmaDel(x){
    idFuncionario = x;

    $( "#exclui" ).dialog("open");
}   

$(document).ready(function(){
        $("#exclui").dialog({
                autoOpen : false,
                modal : true,
                title : "<span class='ui-icon ui-icon-info' style='float:left; margin:1px 7px 0 0;'></span>Alerta do Sistema",
                resizable : false,
                draggable : false,
                buttons: {
                        Confirmar: function() {
                                window.location = "/funcionario/delete/id/" + idFuncionario;
                                $( this ).dialog( "close" );
                        },
                        Cancelar: function() {
                                $( this ).dialog( "close" );
                        }
                        
                }
                        
        });
});
$(document).ready(function(){
        $("#alerta").dialog({
                modal : true,
                title : "<span class='ui-icon ui-icon-info' style='float:left; margin:1px 7px 0 0;'></span>Alerta do Sistema",
                resizable : false,
                draggable : false,
                buttons: {
                        Ok: function() {
                                $( this ).dialog( "close" );
                        }
                }
                        
        });
      
});

$(function() {        
$( ".bt .edit" ).button({
            icons: {
                primary: "ui-icon-pencil"
            },
            text: false
        })  ;
})  ;        
$(function() {        
$( ".bt .del" ).button({
            icons: {
                primary: "ui-icon-trash"
            },
            text: false
        })  ;        
});       

</script>

<div id="createproject" >
<center>
<table width="95%" class="tbl">

        <thead><tr><th>Nome</th><th>Identidade</th><th>Email</th><th>Ações</th></tr></thead>
        <tbody>
        <?
        $indice = 0;
        foreach ( $this->paginator as $aux ) :

            if($indice%2){
                echo "<tr class='odd' >
                        <td width='40%'>".$aux['nome']."</td>
                        <td width='20%'>".$aux['documentoIdentificacao']."</td>
                        <td width='28%'>".$aux['email']."</td>
                        <td>
                            <div class='bt'>
                                <button class='edit' onclick='edita(".$aux['idfuncionario'].")' >Editar Funcionário</button>
                                <button class='del'id='confirmaExclui' onclick='confirmaDel(".$aux['idfuncionario'].")'>Excluir Funcionário</button>
                            </div>
                        </td>                            
                    </tr>
                    </tbody>";
            } else {
                echo "<tr>
                        <td width='40%'>".$aux['nome']."</td>
                        <td width='20%'>".$aux['documentoIdentificacao']."</td>
                        <td width='28%'>".$aux['email']."</td>
                        <td>
                            <div class='bt'>
                                <button class='edit' onclick='edita(".$aux['idfuncionario'].")' >Editar Funcionário</button>
                                <button class='del'id='confirmaExclui' onclick='confirmaDel(".$aux['idfuncionario'].")'>Excluir Funcionário</button>
                            </div>
                        </td>                            
                            
                    </tr>";
            }
         $indice = $indice + 1;
         endforeach; ?>
            </tbody>
</table>

</center>
<br>

<div>
    <center><?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?></center>
</div>
</div>
<div id="exclui">Tem certeza que deseja excluir este Funcionário?</div>
<script>
menu('13');
</script>