<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <script type="text/javascript" src="/js/jquery.js"></script>

    <?php
        $this->jQuery()
            ->setLocalPath('/js/jquery-1.7.2.min.js')
            ->setUiLocalPath('/js/jquery-ui-1.8.21.custom.min.js')
            ->addStylesheet('/css/ui-lightness/jquery-ui-1.8.21.custom.css')
            ->addJavascriptFile('/js/jquery.ui.datepicker-pt-BR.js');
    ?>
    <?php echo $this->jQuery().PHP_EOL; ?>


<title>.: SGCS Farm :.</title>
<script src="/js/javascript.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/css/css.css" />
<?php echo $this->headLink()->appendStylesheet('/css/tabela.css') ?>
<?php echo $this->headLink()->appendStylesheet('/css/tab.css') ?>

</head>


<body>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td background="/images/layout_02.jpg" style="background-repeat:repeat-x">&nbsp;</td>
    <td width="1022"><img src="/images/layout_01.jpg" width="1022" height="52" border="0" /></td>
    <td background="/images/layout_02.jpg" style="background-repeat:repeat-x">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td width="1022" height="127" background="/images/layout_03.jpg">
      <table width="100%" height="127" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="55%">&nbsp;</td>
          <td width="35%" align="right">
              <?php echo $this->dadosIndex->nome ?> <br/>
              <?php echo $this->dadosIndex->nomeEmpresa ?> <br/><br/>
              <a href="/auth/logout" class="linkLaranja" style="font-size:13px">Sair </a><br />
          
         </td>
          <td width="10%"><img src="<?=$this->dadosIndex->foto ?>" width="102px" height="127px" /></td>
        </tr>
      </table>
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td style="background:url('/images/menu_itens_01.jpg') repeat-x">&nbsp;</td>
    <td style="background:url('/images/menu_01.jpg') no-repeat" width="1022" height="70" align="center">
        <div class="divMenu">
            <div onclick="window.open('/index','_self')"><img src="/images/menu_selected_03.jpg" onclick="menu(this.id)" id="1" class="menu" />
                 <img src="/images/menu_unselected_03.jpg" onclick="menu(this.id)" id="11" class="hiddenMenu" />
            </div>
            <div onclick="window.open('/projeto','_self')"><img src="/images/menu_unselected_04.jpg" onclick="menu(this.id)" id="12" class="menu" />
                 <img src="/images/menu_selected_04.jpg" onclick="menu(this.id)" id="2" class="hiddenMenu" />
            </div>
            <div onclick="window.open('/pessoal/meusdados','_self')"><img src="/images/menu_unselected_05.jpg" onclick="menu(this.id)" id="13" class="menu" />
                 <img src="/images/menu_selected_05.jpg" onclick="menu(this.id)" id="3" class="hiddenMenu" />
            </div>
            <div ><img src="/images/menu_unselected_06.jpg" onclick="menu(this.id)" id="14" class="menu" />
                 <img src="/images/menu_selected_06.jpg" onclick="menu(this.id)" id="4" class="hiddenMenu" />
            </div>
            <div ><img src="/images/menu_unselected_07.jpg" onclick="menu(this.id)" id="15" class="menu" />
                 <img src="/images/menu_selected_07.jpg" onclick="menu(this.id)" id="5" class="hiddenMenu" />
            </div>

            
            <?php
            $idImg = 5;
            if ($this->AdminEmpresa){
            $idImg = $idImg + 1;
                    ?>            
            <div onclick="window.open('/funcionario','_self')"><img src="/images/menu_unselected_08.jpg" onclick="menu(this.id)" id="1<?echo $idImg?>" class="menu" />
                 <img src="/images/menu_selected_08.jpg" onclick="menu(this.id)" id="<?echo $idImg?>" class="hiddenMenu" />
            </div>

                             
            <?
            }
            if ($this->AdminFilial){
            $idImg = $idImg + 1;
                    ?>
            <div onclick="window.open('#','_self')"><img src="/images/menu_unselected_09.jpg" onclick="menu(this.id)" id="1<?echo $idImg?>" class="menu" />
                 <img src="/images/menu_selected_09.jpg" onclick="menu(this.id)" id="<?echo $idImg?>" class="hiddenMenu" />
            </div>
            <?                 
            }
            ?>          
            
        </div>
    </td>
    <td style="background:url('/images/menu_itens_01.jpg') repeat-x">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td width="1022">
        <div id="content" style="background-color:#eaeaea; width:1022px; min-height:300px;">

                      <?php echo $this->layout()->content; ?>
        </div>
</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td background="/images/layout_08.jpg" style="background-repeat:repeat-x">&nbsp;</td>
    <td width="1022"><img src="/images/layout_07.jpg" width="1022" /></td>
    <td background="/images/layout_08.jpg" style="background-repeat:repeat-x">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td width="1022"><img src="/images/tela-de-login_09.jpg" width="1022" /></td>
    <td>&nbsp;</td>
  </tr>
</table>
</body>
</html>

