<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />


    <?php
        $this->jQuery()
            ->setLocalPath('/js/jquery-1.7.2.min.js')
            ->setUiLocalPath('/js/jquery-ui-1.8.21.custom.min.js')
            ->addStylesheet('/css/ui-lightness/jquery-ui-1.8.21.custom.css')
            ->addJavascriptFile('/js/jquery.ui.datepicker-pt-BR.js');
    ?>
    <?php echo $this->jQuery().PHP_EOL; ?>


<title>.: SGCS Farm :.</title>
<script src="/js/javascript.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/css/css.css" />
</head>

<body>
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td background="/images/layout_02.jpg" style="background-repeat:repeat-x">&nbsp;</td>
    <td width="1022"><img src="/images/layout_01.jpg" width="1022" height="52" border="0" /></td>
    <td background="/images/layout_02.jpg" style="background-repeat:repeat-x">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td width="1022" height="127" background="/images/layout_03.jpg">
      <table width="100%" height="127" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td width="55%">&nbsp;</td>
          <td width="35%" align="right"><?php echo $this->funcLogado->nome ?> - <a href="/auth/logout" class="linkLaranja" style="font-size:13px">Sair</a><br />
          Funcoes do camarada logado<br />
          Envolvido em X projetos - <a class="linkLaranja" href="#">Visualizar</a><br />
          Possui X tarefas pendentes - <a class="linkLaranja" href="#">Visualizar</a></td>
          <td width="10%">&nbsp;</td>
        </tr>
      </table>
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td width="1022">
	  <table width="100%" height="70" border="0" cellspacing="0" cellpadding="0" >
              <tr>
                  <td>  <a href="/index"><img src="/images/menu_selected_01.jpg" onclick="menu(this.id)" id="1" width="80" height="70" class="menu" />		
                        <img src="/images/menu_unselected_01.jpg" onclick="menu(this.id)" id="11" height="70" class="hiddenMenu" /></a></td>
		    
                  <td>  <a href="/funcionario"><img src="/images/menu_selected_02.jpg" onclick="menu(this.id)" id="2" width="145" height="70" class="hiddenMenu" />	
                        <img src="/images/menu_unselected_02.jpg" onclick="menu(this.id)" id="12" height="70" class="menu" /></a></a></td>
		    
                  <td>  <a href="/projeto"><img src="/images/menu_selected_03.jpg" onclick="menu(this.id)" id="3"  width="156" height="70" class="hiddenMenu" />	
                        <img src="/images/menu_unselected_03.jpg" onclick="menu(this.id)" id="13" height="70" class="menu" /></a></td>
		    
                  <td>  <a href="#"><img src="/images/menu_selected_04.jpg" onclick="menu(this.id)" id="4"  width="175" height="70" class="hiddenMenu" />	
                        <img src="/images/menu_unselected_04.jpg" onclick="menu(this.id)" id="14" height="70" class="menu"/></a></td>
		    
                  <td>  <a href="#"><img src="/images/menu_selected_05.jpg" onclick="menu(this.id)" id="5"  width="156" height="70" class="hiddenMenu" />	
                        <img src="/images/menu_unselected_05.jpg" onclick="menu(this.id)" id="15" height="70" class="menu"/></a></td>
            
                  <td>  <a href="#"><img src="/images/menu_selected_06.jpg" onclick="menu(this.id)" id="6"  width="118" height="70" class="hiddenMenu" />	
                        <img src="/images/menu_unselected_06.jpg" onclick="menu(this.id)" id="16" height="70" class="menu" /></a></td>
            
                  <td>  <a href="#"><img src="/images/menu_selected_07.jpg" onclick="menu(this.id)" id="7"  width="97" height="70" class="hiddenMenu" />	
           		<img src="/images/menu_unselected_07.jpg" onclick="menu(this.id)" id="17" height="70" class="menu" /></a></td>
            
                  <td>  <a href="#"><img src="/images/menu_selected_08.jpg" onclick="menu(this.id)" id="8"  width="95" height="70" class="hiddenMenu" />	
                        <img src="/images/menu_unselected_08.jpg" onclick="menu(this.id)" id="18" height="70" class="menu" /></a></td>
	    </tr>
    </table></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td width="1022">
        <div id="content" style="background-color:#eaeaea; width:1022px; min-height:522px;">
            <?php echo $this->layout()->content; ?>
        </div>
</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td width="1022"><img src="/images/tela-de-login_08.jpg" width="1022" /></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td width="1022"><img src="/images/tela-de-login_09.jpg" width="1022" /></td>
    <td>&nbsp;</td>
  </tr>
</table>
</body>
</html>

