<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />


    <?php
        $this->jQuery()
            ->setLocalPath('/js/jquery-1.7.2.min.js')
            ->setUiLocalPath('/js/jquery-ui-1.8.21.custom.min.js')
            ->addStylesheet('/css/ui-lightness/jquery-ui-1.8.21.custom.css')
            ->addJavascriptFile('/js/jquery.ui.datepicker-pt-BR.js');
    ?>
    <?php echo $this->jQuery().PHP_EOL; ?>



    <title>SGCSFarm</title>

    <style type="text/css">
        *{
          margin:0;
          padding:0;
        }

        body{
          padding:10px;
        }

        #wrapper{
          border:1px solid black;
          margin:0 auto;
          width:900px;
        }

        #header, #footer{
          background-color:#f0f0f0;
          height:170px;
        }

        #content{
          border:1px solid black;
        }
    </style>

</head>
<body>

    <div id="wrapper">
        <div id="header">
            <h1>Header</h1>
            <br/>

            <a href="/index"> <h4>Controler Index </h4> </a>
            <a href="/funcionario"><h4>Controler funcionario</h4></a>
            <a href="/tarefa"><h4>Controler Tarefa</h4></a>
            <a href="/projeto"><h4>Controler Projeto</h4></a>
            <a href="/auth/logout"><h4>Sair</h4></a>
        </div>
        <div id="content">
            <?php echo $this->layout()->content; ?>
        </div>
        <div id="footer">
            Footer
        </div>
    </div>

</body>
</html>