<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>.: SGCS Farm :.</title>
<link rel="stylesheet" type="text/css" href="/css/css.css" />
<link rel="stylesheet" type="text/css" href="/css/ui-lightness/jquery-ui-1.8.21.custom.css"/>    
   
</head>

<body onload="document.login.usuario.focus()">
<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td background="/images/tela-de-login_01.jpg" style="background-repeat:repeat-x">&nbsp;</td>
    <td width="1022"><img src="/images/tela-de-login_02.jpg" width="1022" height="65" usemap="#Map" border="0" /></td>
    <td background="/images/tela-de-login_01.jpg" style="background-repeat:repeat-x">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td width="1022" height="112"><img src="/images/tela-de-login_03.jpg" width="1022" usemap="#Map2" border="0"/></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td width="1022"><img src="/images/tela-de-login_05.jpg" width="1022" /></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td width="1022">


	  <?php echo $this->layout()->content; ?>

	</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td width="1022"><img src="/images/tela-de-login_08.jpg" width="1022" /></td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td width="1022"><img src="/images/tela-de-login_09.jpg" width="1022" /></td>
    <td>&nbsp;</td>
  </tr>
</table>
<map name="Map" id="Map">
  <area shape="rect" coords="704,40,780,62" href="/auth/contato" alt="contato" />
  <area shape="rect" coords="599,39,666,62" href="#" alt="sobre" />
  <area shape="rect" coords="489,39,556,62" href="/auth/index" alt="home" />
  <area shape="rect" coords="981,7,1010,38" href="#" alt="fonteDown" />
  <area shape="rect" coords="939,7,979,37" href="#" alt="fonteUp" />
  <area shape="rect" coords="795,8,920,35" href="#" alt="atalhos" />
  <area shape="rect" coords="73,6,104,32" href="#" alt="ingles" />
  <area shape="rect" coords="39,6,70,32" href="#" alt="espanhol" />
  <area shape="rect" coords="5,7,36,33" href="#" alt="portugues" />
</map>
<map name="Map2" id="Map2">
  <area shape="rect" coords="4,2,351,108" href="#" alt="sgcsfarm" />
</map>
<script src="/js/javascript.js" type="text/javascript"></script>
</body>
</html>