<?
if ( isset($this->flag)  )
      switch ($this->flag){
        case 1:
            echo   "<h3>Filial não cadastra, nome já existente.</h3><br>";
            break;
         }
?>

<form action="/filial/create" method="post">

        <div>
            <h1>Cadastro de Empresa Filial</h1>

            <br><br>

            <label for="nome">Nome:</label>
            <input type="text" id="nome" name="nome" maxlength="35"/>
            <br><br>

            <label for="tel">Telefone:</label>
            <input type="text" id="tel" name="tel" maxlength="25"/>
            <br><br>

            <label for="endereco">Endereço:</label>
            <input type="text" id="endereco" name="endereco" maxlength="25"/>
            <br><br>

          <label for="responsavel">Responsável:</label>
            <select id="responsavel" name="idResponsavel">
                <?php foreach ( $this->funcionario as $responsavel) : ?>
                <option value="<?php echo $responsavel->idfuncionario; ?>">
                    <?php echo $responsavel->nome; ?></option>
                <?php endforeach; ?>
            </select>
            <br><br>

            <label for="email">E-mail:</label>
            <input type="text" id="email" name="email" maxlength="25"/>
            <br><br>

             <label for="cep">CEP:</label>
            <input type="text" id="cep" name="cep" maxlength="25"/>
            <br><br>

            <input  type="submit" value="Cadastrar" name="Cadastrar" />
            <br><br>
        </div>

</form>

