<form action="/empresafilial/edit" method="post">

        <div>
            <br><br>
            <label for="filial">Filial:</label>
            <select id="filial" name="idFilial">
                <?php foreach ( $this->filial as $filial ) : ?>
                <option <?php
                        if ( $filial->idempresaFilial == $this->funcionario->empresaFilial_idempresaFilial )
                        echo 'selected="selected"';
                        ?>
                        value="<?php echo $filial->idempresaFilial; ?>">
                    
                    <?php echo $filial->nome; ?>
                </option>
                <?php endforeach; ?>
            </select>
            <br><br>

            <input type="hidden" value="<?=$this->empresaFilial->idempresaFilial;?>" name="id" />
            
            <label for="idempresaFilial">ID Empresa Filial:</label>
            <input type="text" id="idempresaFilial" name="idempresaFilial" maxlength="35" value ="<?= $this->empresaFilial->idempresaFilial; ?>"/>
            <br><br>

            <label for="nome">Nome:</label>
            <input type="text" id="nome" name="nome" maxlength="25" value ="<?= $this->empresaFilial->nome; ?>"/>
            <br><br>

            <label for="tel">Telefone:</label>
            <input type="text" id="tel" name="tel" maxlength="25"  value ="<?= $this->empresaFilial->tel; ?>"/>
            <br><br>

            <label for="endereco">Endereço:</label>
            <input type="text" id="endereco" name="endereco" maxlength="25"  value ="<?= $this->empresaFilial->endereco; ?>"/>
            <br><br>
            
            <label for="endereco">Endereço:</label>
            <input type="text" id="endereco" name="endereco" maxlength="25"  value ="<?= $this->empresaFilial->endereco; ?>"/>
            <br><br>
            
            <label for="email">E-mail:</label>
            <input type="text" id="email" name="email" maxlength="25"  value ="<?= $this->empresaFilial->email; ?>"/>
            <br><br>

            <input  type="submit" value="atualizar" name="Atualizar" />
            <br><br>
        </div>

</form>