<ul id="globalnav">
  <li><a href="/funcionario/indexemp" >Funcionarios</a></li>
  <li><a href="/funcionario/createemp">Cadastrar Reponsável</a></li>
  <li><a href="/filial" >Filiais</a></li>
  <li><a href="/filial/create">Cadastrar Filial</a></li>
  <li><a href="/projeto/admingeral">Projetos da Empresa</a></li>
  <li><a href="/filial/edit" class="here">Editar Filial</a></li>
</ul>


<?
if ( isset($this->flag)  )
      switch ($this->flag){
          case 1:
            echo   "<h3>Filial não atualizada, nome já existente.</h3><br>";
            break;
          case 2:
            echo   "<h3>Erro: o responsavel não pode ser trocado, verifique se ele não esta vinculado a algum projeto como colaborador ou como gerente</h3><br>";
            break;
         }
?>

 <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/jquery.validate.js"></script>
    <script type="text/javascript" src="/js/jquery.maskedinput-1.3.js"></script>
    <script type="text/javascript" src="/js/validaForm.js"></script>
<script type="text/javascript">

$(document).ready(function(){

	$("#createfilial").validate({
		// Define as regras
		rules:{
			nome:{
				// campoNome será obrigatório (required) e terá tamanho mínimo (minLength)
				required: true, minlength: 3
			},
			tel:{
				// campoEmail será obrigatório (required) e precisará ser um e-mail válido (email)
				required: true, minlength: 10
			},
			endereco:{
				required: true, minlength:10
			},
                        responsavel:{
                                required:true
                        },
                        email:{
                                required:true,email:true
                        },
                        cep:{
                                required:true, minlength:8
                        }
                }
		// Define as mensagens de erro para cada regra
		/*messages:{
			name:{
				required: "Campo obrigatório!",
				minlength: "O nome do projeto deve conter, no mínimo, 3 caracteres"
			},
			descricao:{
				required: "Campo obrigatório!",
				minlength: "A descrição do projeto deve conter, no mínimo, 10 caracteres"
			},
			dtinicio:{
				required: "Campo obrigatório!"
			}
		}*/
	});

});
</script>
<div id="createproject" >
<form id="createfilial" class="rounded" action="/filial/edit" method="post">

        <div>
            <center><h3>Atualizar Filial</h3></center>

            <input type="hidden" value="<?=$this->filial->idempresaFilial;?>" name="idfilial" />
            <input type="hidden" value="<?=$this->filial->responsavel;?>" name="idresp" />
            <input type="hidden" value="<?=$this->filial->nome;?>" name="filialnome" />

            <div class="field">
            <label for="nome" class="lblGeralClass">Nome:</label>
            <input type="text" class="input" id="nome" name="nome" maxlength="35" value ="<?= $this->filial->nome; ?>"/>
            </div>

            <div class="field">
            <label for="tel" class="lblGeralClass">Telefone:</label>
            <input type="text" class="input" id="tel" name="tel" maxlength="25"   value ="<?= $this->filial->tel; ?>"/>
            </div>

            <div class="field">
            <label for="endereco" class="lblGeralClass">Endereço:</label>
            <input type="text" class="input" id="endereco" name="endereco" maxlength="25"  value ="<?= $this->filial->endereco; ?>"/>
            </div>

            <div class="field">
          <label for="responsavel" class="lblGeralClass">Responsável:</label>
            <select id="responsavel" name="idResponsavel" class="select">

                <option value="<?php echo $this->responsavel->idfuncionario; ?>" selected="selected">
                    <?php echo $this->responsavel->nome; ?></option>

                <?php foreach ( $this->funcionario as $responsavel) : ?>
                <option value="<?php echo $responsavel->idfuncionario; ?>">
                    <?php echo $responsavel->nome; ?></option>
                <?php endforeach; ?>
            </select>
            </div>

            <div class="field">
            <label for="email" class="lblGeralClass">E-mail:</label>
            <input type="text" class="input" id="email" name="email" maxlength="25"  value ="<?= $this->filial->email; ?>"/>

            </div>

            <div class="field">
            <label for="cep" class="lblGeralClass">CEP:</label>
            <input type="text" class="input" id="cep" name="cep" maxlength="25"  value ="<?= $this->filial->cep; ?>"/>
            </div>


            <input  type="submit" id="x" value="Aualizar" name="Atualizar" class="button" style="width: 135px"/>
            <input  type="reset" value="Limpar" name="Limpar" class="button" style="width: 135px" />
            <br><br>
        </div>

</form>

</div>