<?
if ( isset($this->flag)  )

         switch ($this->flag){
        case 1:
            echo   "<div id='alerta'>Filial cadastrada com sucesso!</div>";
            break;
        case 2:
            echo   "<div id='alerta'>Filial atualizada com sucesso!</div>";
            break;
        case 3:
            echo "<div id='alerta'>Filial excluída com sucesso!</div>";
            break;
         }
?>

<ul id="globalnav">
  <li><a href="/funcionario/indexemp" >Funcionarios</a></li>
  <li><a href="/funcionario/createemp">Cadastrar Reponsável</a></li>
  <li><a href="#" class="here">Filiais</a></li>
  <li><a href="/filial/create" >Cadastrar Filial</a></li>
  <li><a href="/projeto/admingeral">Projetos da Empresa</a></li>
</ul>

<div id="createproject" >
<center>
    <table width="95%" class="tbl">

        <thead><tr><th>Nome</th><th>Telefone</th><th>Endereço</th><th>Email</th><th>Cep</th><th></th><th></th></tr></thead>
        <tbody>
        <?
        foreach ( $this->filial as $aux ) :

            echo "<tr>
                    <td>".$aux->nome."</td>
                    <td>".$aux->tel."</td>
                    <td>".$aux->endereco."</td>
                    <td>".$aux->email."</td>
                    <td>".$aux->cep."</td>

                    <td><a href='/empresafilial/edit/id/".$aux->idempresaFilial."' >Editar</a></td>
                    <td><a href='/empresafilial/delete/id/".$aux->idempresaFilial."' >Excluir</a></td>
                  </tr>";

         endforeach; ?>
        </tbody>
</table>
</center>
</div>