<?php

require_once dirname(__FILE__) . '/../../../application/controllers/FilialController.php';

/**
 * Test class for FilialController.
 * Generated by PHPUnit on 2012-07-11 at 04:31:31.
 */
class FilialControllerTest extends Zend_Test_PHPUnit_ControllerTestCase {

    /**
     * @var FilialController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        // Assign and instantiate in one step:
        $this->bootstrap = new Zend_Application(
        APPLICATION_ENV,
        APPLICATION_PATH
           . '/configs/application.ini'
        );
        parent::setUp();
        
        $this->funcionario = new Model_DbTable_Func();
        $this->filial = new Model_DbTable_Filial();
        $this->colaboradores = new Model_DbTable_Colaboradores();
        $this->projeto = new Model_DbTable_Proj();
        Zend_Controller_Front::getInstance()->setParam('noErrorHandler',true)->throwExceptions(true); 
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testInit().
     */
    public function testInit() {
        $this->request->setMethod('POST')
              ->setPost(array(
                  'login' => 'mimoso',
                  'senha' => '1234'
              ));
        $this->dispatch('/Auth/login');
        $this->assertController('Auth');
        $this->assertAction('login');        
        
        $this->dispatch('/filial/Init');
        $this->assertController('filial');
        $this->assertAction('Init');
    }

    /**
     * @todo Implement testIndexAction().
     */
    public function testIndexAction() {
        $this->request->setMethod('POST')
              ->setPost(array(
                  'login' => 'mimoso',
                  'senha' => '1234'
              ));
        $this->dispatch('/filial/login');
        $this->assertController('filial');
        $this->assertAction('login');        
        
        $this->dispatch('/filial/index');
        $this->assertController('filial');
        $this->assertAction('index');
    }

    /**
     * @todo Implement testCreateAction().
     */
    public function testCreateAction() {
        $this->request->setMethod('POST')
              ->setPost(array(
                  'login' => 'mimoso',
                  'senha' => '1234'
              ));
        
         $this->dispatch('/Auth/login');
         $this->request->setMethod('POST')
              ->setPost(array(
                'nome'  => 'SoftArms',
                'tel' => '7788998877',
                'endereco'  => 'rua dos carroceiros',
                'responsavel'  => 'ze das farinhas',
                'email'  => 'Farinhas@colombia.com',
                'cep' => '45999-140'
              ));
         
         $this->dispatch('/filial/create');
         $this->assertRedirectTo('/filial/index/flag/1');
                
    }
    
    
    
     public function testEditAction() {
        $this->request->setMethod('POST')
              ->setPost(array(
                  'login' => 'mimoso',
                  'senha' => '1234'
              ));
        
         $this->dispatch('/Auth/login');
         $this->request->setMethod('POST')
              ->setPost(array(
                'nome'  => 'SoftArms',
                'tel' => '7788998877',
                'endereco'  => 'rua dos carroceiros',
                'responsavel'  => 'ze das farinhas',
                'email'  => 'Farinhas@colombia.com',
                'cep' => '45999-140'
              ));
         
         $this->dispatch('/filial/create');
         $this->assertRedirectTo('/filial/index/flag/1');
         
         $select = $this->filial->select();
         $select->from($this->filial, 'idempresaFilial');
         $select->where('nome = ?', 'SoftArms');
        
         $this->request->setMethod('POST')
              ->setPost(array(
                'nome'  => 'SoftBrArms',
                'tel' => '7788998877',
                'endereco'  => 'rua dos carroceiros',
                'responsavel'  => 'ze das farinhas',
                'email'  => 'Farinhas@brasil.com',
                'cep' => '45999-140'
              ));
         
         $this->dispatch('filial/edit/id/' + $this->filial->fetchRow($select)->idempresaFilial );
         $this->assertRedirectTo('/filial/index/flag/2'); 
         
                
    }
    
    
     public function testDeleteAction() {
        $this->request->setMethod('POST')
              ->setPost(array(
                  'login' => 'mimoso',
                  'senha' => '1234'
              ));
        
         $this->dispatch('/Auth/login');
         $this->request->setMethod('POST')
              ->setPost(array(
                'nome'  => 'SoftArms',
                'tel' => '7788998877',
                'endereco'  => 'rua dos carroceiros',
                'responsavel'  => 'ze das farinhas',
                'email'  => 'Farinhas@colombia.com',
                'cep' => '45999-140'
              ));
         
         $this->dispatch('/filial/create');
         $this->assertRedirectTo('/filial/index/flag/1');
                
        $select = $this->filial->select();
        $select->from($this->filial, 'idempresaFilial');
        $select->where('nome = ?', 'SoftArms');
        
        $this->dispatch('filial/delete/id/' + $this->filial->fetchRow($select)->idempresaFilial );
        $this->assertRedirectTo('/filial/index/flag/3'); 
         
    }

    
    
}

?>
