<?php

/**
 * Classe de teste do IndexController, essa classe possui métodos que realizam testes para validar
 * o funcionamento do IndexController.
 * Generated by PHPUnit on 2012-07-10 at 02:21:57.
 * @author Luiz Daud
 * @version 0.1
 * @access public
 */
class IndexControllerTeste extends Zend_Test_PHPUnit_ControllerTestCase
{
     /**
     * Funcao que inicializa todos os parametros necessarios para o correto
     * funcionamento dos testes, como conexões com o banco de dados e
     * variaveis de controle dos testes.
     *
     * @author Luiz Daud
     * @access public
     * @return void
     *
     */
    
    public function setUp()    {
          // Assign and instantiate in one step:
        $this->bootstrap = new Zend_Application(
        APPLICATION_ENV,
        APPLICATION_PATH
           . '/configs/application.ini'
        );
        parent::setUp();
    
    }
    
    /**
     * Função que verifica se a home page está sendo alcançada corretamente.
     *
     * @author Luiz Daud
     * @access public
     * @return void
     */
    
    public function testHomePageIsASuccessfulRequest() {
        //faz login        
        $this->request->setMethod('POST')
              ->setPost(array(
                  'login' => 'mimoso',
                  'senha' => '1234'
              ));
        $this->dispatch('/Auth/login');
        //verifica os controllers
        $this->assertController('Auth');
        $this->assertAction('login');
        //verifica se alguma exeception é lançada
        $this->assertFalse($this->response
                        ->isException());
        //verifica o redirecionamento pra pagina inicial
        $this->assertRedirectTo('/');
    }
 
    public function tearDown() {
        /* Tear Down Routine */
    }
}

?>
