<?php

require_once dirname(__FILE__) . '/../../../application/controllers/PessoalController.php';

/**
 * Test class for PessoalController.
 * Generated by PHPUnit on 2012-07-11 at 04:31:48.
 */
class PessoalControllerTest extends Zend_Test_PHPUnit_ControllerTestCase {

    /**
     * @var PessoalController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        // Assign and instantiate in one step:
        $this->bootstrap = new Zend_Application(
        APPLICATION_ENV,
        APPLICATION_PATH
           . '/configs/application.ini'
        );
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testInit().
     */
    public function testInit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testEditAction().
     */
    public function testEditAction() {
        $this->request->setMethod('POST')
              ->setPost(array(
                  'nome' => 'mimoso',
                  'doc' => '123987',
                  'login' => 'mimosos',
                  'email' => 'mimoso@softfarm.com'
              ));
        $this->dispatch('/pessoal/edit');
        $this->assertRedirectTo(pessoal/meusdados/flag/1);                
    }

    /**
     * @todo Implement testImagemAction().
     */
    public function testImagemAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMeusdadosAction().
     */
    public function testMeusdadosAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSenhaAction().
     */
    public function testSenhaAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
