<?php

require_once dirname(__FILE__) . '/../../../application/controllers/PessoalController.php';

/**
 * Test class for PessoalController.
 * Generated by PHPUnit on 2012-07-11 at 04:31:48.
 */
class PessoalControllerTest extends Zend_Test_PHPUnit_ControllerTestCase {

    /**
     * @var PessoalController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        // Assign and instantiate in one step:
        $this->bootstrap = new Zend_Application(
        APPLICATION_ENV,
        APPLICATION_PATH
           . '/configs/application.ini'
        );
        parent::setUp();
        Zend_Controller_Front::getInstance()->setParam('noErrorHandler',true)->throwExceptions(true); 
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testInit().
     */
    public function testInit() {
        $this->request->setMethod('POST')
              ->setPost(array(
                  'login' => 'mimoso',
                  'senha' => '1234'
              ));
        $this->dispatch('/Auth/login');
        $this->assertController('Auth');
        $this->assertAction('login');      
        
        $this->dispatch('/Auth/Init');
        $this->assertController('Auth');
        $this->assertAction('Init');
    }

    /**
     * @todo Implement testEditAction().
     */
    public function testEditAction() {
        $this->request->setMethod('POST')
              ->setPost(array(
                  'login' => 'mimoso',
                  'senha' => '1234'
              ));
        $this->dispatch('/Auth/login');        
        
        $this->request->setMethod('POST')
              ->setPost(array(
                  'nome' => 'Geovane Mimoso',
                  'doc' => '987654',
                  'login' => 'mimoso',
                  'email' => 'mimoso@softfarm.com'
              ));
        $this->dispatch('/pessoal/edit');
        $this->assertController('pessoal');
        $this->assertAction('edit');
        $this->assertRedirectTo('/pessoal/meusdados/flag/1');
    }

    /**
     * @todo Implement testImagemAction().
     */
    public function testImagemAction() {
        $this->request->setMethod('POST')
              ->setPost(array(
                  'login' => 'mimoso',
                  'senha' => '1234'
              ));
        $this->dispatch('/Auth/login');
        $this->assertController('Auth');
        $this->assertAction('login');        
        
        $this->dispatch('/pessoal/imagem');
        $this->assertController('pessoal');
        $this->assertAction('imagem');
    }

    /**
     * @todo Implement testMeusdadosAction().
     */
    public function testMeusdadosAction() {
        // Remove the following lines when you implement this test.
        $this->request->setMethod('POST')
              ->setPost(array(
                  'login' => 'mimoso',
                  'senha' => '1234'
              ));
        $this->dispatch('/Auth/login', 'login');       
        $this->dispatch('/pessoal/meusdados');
        $this->assertController('pessoal');
        $this->assertAction('meusdados');
    }

    /**
     * @todo Implement testSenhaAction().
     * testa a alteração de senha
     */
    public function testSenhaAction() {
       $this->request->setMethod('POST')
              ->setPost(array(
                  'login' => 'mimoso',
                  'senha' => '1234'
              ));
        $this->dispatch('/Auth/login');
        
        $this->request->setMethod('POST')
              ->setPost(array(
                  'senhaAtual' => '1234',
                  'senhaNova' => '1234',
                  'senhaNova2' => '1234',             
              ));
        $this->dispatch('/pessoal/senha');
        $this->assertController('pessoal');
        $this->assertAction('senha');
        $this->assertRedirectTo('/pessoal/meusdados/flag/3');
        }
        
}

?>
