<?php echo $this->headLink()->appendStylesheet('/css/tabela.css')
                           ->appendStylesheet('/css/projetos_css.css'); ?>

<ul id="globalnav">
  <li><a href="/funcionario/index">Funcionarios</a></li>
  <li><a href="/funcionario/create">Cadastrar Funcionário</a></li>
  <li><a href="#" class="here">Projetos</a></li>
  <li><a href="/projeto/create" >Criar Projeto</a></li>
</ul>

<br>

<div id="projetos">
    <center><h3>Projetos da Filial: <?php echo $this->nomeFilial; ?></h3></center>
    <?php if(count($this->paginator) == 0) {?>
        <br/>
        <center>
            <h4>Esta Filial ainda não possui projetos.</h4>
        </center>
    <?php }?>
    <?php foreach ( $this->paginator as $aux ) : ?>
        <center>
        <div id="projetos_conteudo">
                Nome: <?php echo $aux['nomeProj']; ?><br />
                Resumo: <?php echo substr($aux['descricao'], 0, 50)."..."; ?><br />
                Data de in&iacute;cio: <?php echo $aux['dataInc']; ?><br />
                Situa&ccedil&atilde;o do projeto: <?php echo $this->estadoProj->buscaEstadoProj($aux['idprojeto']); ?><br/>
                <?php if($this->estadoProj->buscaEstadoProj($aux['idprojeto']) == "Concluido"){ ?>
                    Data de Término: <?php echo $aux['dataFim']; ?><br />
                <?php }?>
                <?php if($this->idFuncLogado == $aux['idGerente']){?>
                    <b>Gerente: <?php echo $aux['nome']; ?></b><br />
                <?php }else{ ?>
                     Gerente: <?php echo $aux['nome']; ?><br />
                <?php } ?>
                E-mail do Gerente:  <?php echo $aux['email']; ?><br />
                <br/>
                <a href='/projeto/detalhesadminfilial/idProj/<?php echo $aux['idprojeto']; ?>'>Acessar Projeto</a>
        </div>
        </center>
    <?php endforeach; ?>
    <br/>
    <div>
    <center><?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?></center>
    </div>
    <br/>
</div>

<script>
menu('17');
</script>