<?php echo $this->headLink()->appendStylesheet('/css/tabela.css')
                           ->appendStylesheet('/css/projetos_css.css'); ?>

<ul id="globalnav">
  <li><a href="/funcionario/indexemp" >Funcionarios</a></li>
  <li><a href="/funcionario/createemp">Cadastrar Reponsável</a></li>
  <li><a href="/filial" >Filiais</a></li>
   <li><a href="/filial/create" >Cadastrar Filial</a></li>
  <li><a href="#" class="here">Projetos da Empresa</a></li>
</ul>
<br>
<div id="projetos">
    <br/>
    <center><h2>Projetos da <?php echo $this->nomeEmpresa; ?></h2></center>
    <br/>
    <?php foreach ( $this->paginator as $aux ) : ?>
        <center>
        <div id="projetos_conteudo">
                Nome: <?php echo $aux['nome']; ?><br />
                Resumo: <?php echo substr($aux['descricao'], 0, 50)."..."; ?><br />
                Data de in&iacute;cio: <?php echo $aux['dataInc']; ?><br />
                Situa&ccedil&atilde;o do projeto: <?php echo $this->estadoProj->buscaEstadoProj($aux['idprojeto']); ?><br/>
                <?php if($this->estadoProj->buscaEstadoProj($aux['idprojeto']) == "Concluido"){ ?>
                    Data de Término: <?php echo $aux['dataFim']; ?><br />
                <?php }?>
                <a href='/projeto/detalhesadmingeral/idProj/<?php echo $aux['idprojeto']; ?>'>Acessar Projeto</a>
        </div>
        </center>
    <?php endforeach; ?>
    <br/>
    <div>
    <center><?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?></center>
    </div>
    <br/>
</div>

<script>
menu('16');
</script>