<?php echo $this->headLink()->appendStylesheet('/css/tabela.css')
                           ->appendStylesheet('/css/projetos_css.css'); ?>
<br/>
<div id="projetos">
    <br/>
    <center><h2>Projetos da Filial: <?php echo $this->nomeFilial; ?></h2></center>
    <br/>
    <?php foreach ( $this->paginator as $aux ) : ?>
        <center>
        <div id="projetos_conteudo">
                Nome: <?php echo $aux['nomeProj']; ?><br />
                Resumo: <?php echo substr($aux['descricaoProj'], 0, 50)."..."; ?><br />
                Data de in&iacute;cio: <?php echo $aux['dataInc']; ?><br />
                Previs&atilde;o de conclus&atilde;o: <?php echo $aux['dataFim']; ?><br />
                Situa&ccedil&atilde;o do projeto: <?php echo $aux['estadoProj']; ?><br/>
               
                <?php if($this->idFuncLogado == $aux['idGerente']){?>
                    <b>Gerente: <?php echo $aux['nomeGerente']; ?></b><br />
                <?php }else{ ?>
                     Gerente: <?php echo $aux['nomeGerente']; ?><br />
                <?php } ?>
                <br/>
                <a href='/projeto/detalhes/idProj/<?php echo $aux['idprojeto']; ?>'>Acessar Projeto</a>
        </div>
        </center>
    <?php endforeach; ?>
    <br/>
    <div>
    <center><?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?></center>
    </div>
    <br/>
</div>

<script>
menu('13');
</script>