<?php echo $this->headLink()->appendStylesheet('/css/contato.css') ?>

<form id="createproject" class="rounded" action="/projeto/create" method="post"q>
    <center><h3>Novo Projeto</h3></center><br>
        <div class="field">            
            <label for="nome">Nome:</label>
            <input type="text" class="input" id="nome" name="nome" maxlength="35"/>
            <p class="hint">Insira o seu nome.</p>
        </div>

        <div class="field">      
            <label for="descricao">Descrição:</label>
            <input type="text" class="input" id="descricao" name="descricao" maxlength="25"/>
            <p class="hint">Insira a descrição do projeto.</p>
        </div>
            
        <div class="field">      
            <label for="dtinicio">Data de Início:</label>
            <input type="date" class="input" id="dtinicio" name="dtinicio" />
            <p class="hint">Defina a data de início do projeto.</p>
        </div>
            
        <div class="field">                  
            <label for="gerente">Gerente:</label>
            <select id="gerente" name="idGerente">
                <?php foreach ( $this->funcionario as $gerente) : ?>
                <option value="<?php echo $gerente->idfuncionario; ?>">
                    <?php echo $gerente->nome; ?></option>
                <?php endforeach; ?>
            </select>
            <p class="hint">Escolha um gerente para o projeto.</p>
        </div>
<br>
    <input  type="submit" value="Cadastrar" name="Cadastrar" class="btnLogin" style="width: 135px" />
    <input  type="reset" value="Limpar" name="Limpar" class="btnLogin" style="width: 135px" />
</form>    
    

<script>
menu('13');
</script>
