<?
if(isset($this->mensagem))
    echo $this->mensagem;
?>

<ul id="globalnav">
  <li><a href="/funcionario/index">Funcionarios</a></li>
  <li><a href="/funcionario/create">Cadastrar Funcionário</a></li>
  <li><a href="/projeto/adminfilial">Projetos</a></li>
  <li><a href="#" class="here">Criar Projeto</a></li>
</ul>

<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery.validate.js"></script>
<script type="text/javascript" src="/js/jquery.maskedinput-1.3.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){
    $("#dtinicio").mask("99/99/9999");
});    
$(document).ready(function(){
        
	$("#createproject").validate({
		// Define as regras
		rules:{
			nome:{
				required: true, minlength: 3
			},
			descricao:{
				required: true, minlength: 10
			},
			dtinicio:{
				required: true
			}
                }
	});
      
});
$(document).ready(function(){
        $("#alerta").dialog({
                modal : true,
                title : "<span class='ui-icon ui-icon-info' style='float:left; margin:1px 7px 0 0;'></span>Alerta do Sistema",
                resizable : false,
                draggable : false,
                buttons: {
                        Ok: function() {
                                $( this ).dialog( "close" );
                        }
                }
                        
        });
      
});
</script>

<br>
<form id="createproject" class="rounded" action="/projeto/create" method="post"q>
    <center><h3>Novo Projeto</h3></center><br>
        <div class="field">            
            <label for="name" class="lblGeralClass">Nome:</label>
            <input type="text" class="input" id="nome" name="nome" maxlength="35"/>
        </div>

        <div class="field">      
            <label for="descricao" class="lblGeralClass">Descrição:</label>
            <textarea class="input" name="descricao" id="descricao"></textarea>
        </div>
            
   
    <div class="field">      
            <label for="dtinicio" class="lblGeralClass">Data de início:</label>
            <?php
                $data = new ZendX_JQuery_Form_Element_DatePicker("dp1",'', array(
                        "defaultDate" => date('Y/m/d', time())));
                $data->setName("dtinicio")
                    ->setAttrib("id", "dtinicio")
                    ->setAttrib("class", "input");
                echo $data;
                ?>
        </div>
           
        <div class="field">                  
            <label for="gerente" class="lblGeralClass">Gerente:</label>
            <select id="gerente" name="idGerente" class="select">
                <?php foreach ( $this->funcionario as $gerente) : ?>
                <option value="<?php echo $gerente->idfuncionario; ?>">
                    <?php echo $gerente->nome; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
<br>
    <input  type="submit" id="x" value="Cadastrar" name="Cadastrar" class="button" style="width: 135px" />
    <input  type="reset" value="Limpar" name="Limpar" class="button" style="width: 135px" />
</form>    
    

<script>
menu('17');
</script>
