<?php echo $this->headLink()->appendStylesheet('/css/tabela.css')
                           ->appendStylesheet('/css/projetos_css.css');
?>
<div id="projetos_detalhes"
     <?php if(($this->idFuncLogado == $this->ProjEncontrado->current()->idGerente)){?>
            style="-moz-box-shadow: 10px 10px 5px #ffb706; /* Firefox 3.6 and earlier */
                    box-shadow: 0px 5px 10px #ffb706;"
    <?php } ?>
>
    <div  id="projetos_detalhes_conteudo">
        <h1 style="color: #fd8f12;"><b><?php echo $this->ProjEncontrado->current()->nomeProj; ?></b></h1><br /><br />
        <h3>Alocado na filial: <span style="color: #ff8000;"><?php echo $this->ProjEncontrado->current()->nomeFilialProj; ?></span></h3><br />
        
        Data de in&iacute;cio: <b><?php echo $this->ProjEncontrado->current()->dataInc; ?></b><br /><br />
        Previs&atilde;o de conclus&atilde;o: <b><?php echo $this->ProjEncontrado->current()->dataFim; ?></b><br /><br />
        Situa&ccedil&atilde;o do projeto: <b><?php echo $this->ProjEncontrado->current()->estadoProj; ?></b><br /><br />
        <?php if(($this->idFuncLogado == $this->ProjEncontrado->current()->idGerente)){?>
            <b>Gerente: <?php echo $this->ProjEncontrado->current()->nomeGerente; ?></b><br /><br />
        <?php }else{ ?>
            Gerente: <?php echo $this->ProjEncontrado->current()->nomeGerente; ?><br /><br />
        <?php } ?>
        <br/>
        Descrição:
        <center>
        <div style="border:3px solid #a1a1a1;
                    border-radius:5px; 
                    word-wrap:break-word; width:70%; border: 1px solid #666666; "><?php echo $this->ProjEncontrado->current()->descricaoProj; ?></div><br />
        </center>

        <center>
            <?php if(($this->idFuncLogado == $this->ProjEncontrado->current()->idGerente)){?>
            <div class="divGerente" style="width: 200px">
                <a title="editar projeto"href='/projeto/edit/id/<?php echo $this->ProjEncontrado->current()->idprojeto; ?>'>
                    <img src="/images/b_edit.png" width="20px;" height="20px" alt="editar projeto"/></a> |
                <a title="excluir projeto" href='/projeto/delete/id/<?php echo $this->ProjEncontrado->current()->idprojeto; ?>'>
                    <img src="/images/b_drop.png" width="20px;" height="20px" alt="excluir projeto"/></a>
            </div>
            <?php } ?>
        </center>
    </div>            
</div>

<!-- div de tarefas -->

<div id="projetos_detalhes_tarefas">
    <center><h4>Tarefas do Projeto: <?php echo $this->ProjEncontrado->current()->nomeProj; ?></h4></center>
    <br/>
    <?php if($this->naoColabEnaoEGerente == '1'){
            if(($this->idFuncLogado == $this->ProjEncontrado->current()->idGerente)){?>
                <center>
                    <a title="Gerenciar Tarefas" href='/tarefa/prepara/idProj/<?php echo $this->ProjEncontrado->current()->idprojeto; ?>'>
                        <div class="divGerente" style="width: 100px">

                                <img src="/images/b_tblops.png" width="30px;" height="30px" alt="Gerenciar Tarefas"/><br/>
                                Gerenciar Tarefas
                        </div>
                    </a>
                </center>
    <?php   } else { ?>
    <center>
        <div style="width: 130px;
                    border:1px solid #a1a1a1;
                    border-radius:10px;
                    display: block;
                    -moz-box-shadow: 10px 10px 5px #888888; /* Firefox 3.6 and earlier */
                    box-shadow: 0px 5px 10px #888888;
        ">
            <a title="Suas Tarefas" href='/tarefa/minhas-tarefas/idProj/<?php echo $this->ProjEncontrado->current()->idprojeto; ?>'>
                Veja suas tarefas<br/>
                <img src="/images/b_bookmark.png" width="30px;" height="30px" alt="Suas Tarefas"/>
            </a>
        </div>
    </center>
    <?php } 
    }?>
    <br>
    <center>
        <div style="width:95%;">
        <table width="100%" class="tbl">
            <thead><tr><th></th><th>Nome Funcionário</th><th>Descrição</th></thead>
    <?php 
        $indice = 0;
        foreach ( $this->paginator as $auxtipoEstadoTarefaColabProj ):
            $detalhes = "";
            $detalhes = $detalhes."<h3>Estado da Tarefa:</h3>".$auxtipoEstadoTarefaColabProj->tipoDeEstado."<br/><br/>";
            $detalhes = $detalhes."<h3>Descrição:</h3><br/>".$auxtipoEstadoTarefaColabProj->descricaoTarefa."<br/><br/>";
            $detalhes = $detalhes."<h4>Data de Início:</h4> ".$auxtipoEstadoTarefaColabProj->dataInc."<br/>";
            $detalhes = $detalhes."<h4>Data de Fim:</h4> ".$auxtipoEstadoTarefaColabProj->dataFim."<br/>";
            if($indice%2){
                echo "<tr class='odd' >
                        <td width='3%' align='center'><a rel='tooltip' id='$detalhes'><img src='/images/lente.png' alt='veja mais' height=24px; width=24px; /></a></td>
                        <td width='10%' align='center' ><p style='word-wrap:break-word;'>".$auxtipoEstadoTarefaColabProj->nomeFunc."</p></td>
                        <td width='15%' align='center'>".substr($auxtipoEstadoTarefaColabProj->descricaoTarefa, 0 , 20)."...</td>
                        </tbody>";
            } else {
                echo "<tr>
                        <td width='3%' align='center'><a rel='tooltip' id='$detalhes'><img src='/images/lente.png' alt='veja mais' height=24px; width=24px; /></a></td>
                        <td width='10%' align='center'><p style='word-wrap:break-word;'>".$auxtipoEstadoTarefaColabProj->nomeFunc."</p></td>
                        <td width='15%' align='center'>".substr($auxtipoEstadoTarefaColabProj->descricaoTarefa, 0 , 20)."...</td>
                    </tr>";
            }
            $indice = $indice + 1;   
        endforeach; ?>
        </table>
            
        <div>
            <center><?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?></center>
        </div>
        </div>
    </center>

</div>

<!-- div de colaboradores -->

<div id="projetos_detalhes_colaboradores">
    <center><h4>Colaboradores do Projeto: <?php echo $this->ProjEncontrado->current()->nomeProj; ?></h4></center>
    <br/>
    <?php if(($this->idFuncLogado == $this->ProjEncontrado->current()->idGerente)){?>
    <center>
        <a title="Gerenciar Colaboradores" href='/colaborador/index/id/<?php echo $this->ProjEncontrado->current()->idprojeto; ?>' >
            <div class="divGerente" style="width: 200px">
                <img src="/images/b_tblops.png" width="30px;" height="30px" alt="Gerenciar Colaboradores"/><br/>
                Gerenciar Colaboradores
            </div>
        </a>
    </center>
    <br>
    <br>
    <?php } ?>
    <center>
        <div style="width:95%;">
        <table width="100%" class="tbl">
            <thead><tr><th>Nome Funcionário</th><th>Função</th><th>E-mail</th></thead>
    <?php
        $indice = 0;
        foreach ( $this->colab as $auxfuncaoColabProj ): 
            if($indice%2){
                echo "<tr class='odd' >
                        <td width='10%'><p style='word-wrap:break-word;'>".$auxfuncaoColabProj->nomeFuncinario."</p></td>
                        <td width='15%' align='center'>".$auxfuncaoColabProj->funcao."</td>
                        <td width='8%' align='center'>".$auxfuncaoColabProj->emailFuncinario."</td>
                    </tr>
                    </tbody>";
            } else {
                echo "<tr>
                        <td width='10%'><p style='word-wrap:break-word;'>".$auxfuncaoColabProj->nomeFuncinario."</p></td>
                        <td width='15%' align='center'>".$auxfuncaoColabProj->funcao."</td>
                        <td width='8%' align='center'>".$auxfuncaoColabProj->emailFuncinario."</td>
                    </tr>";
            }
            $indice = $indice + 1;   
        endforeach; ?>
        </table>
        </div>
    </center>
</div>


<script>
menu('12');
</script>

<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript">

$(function(){
   
   $("*[rel=tooltip]").hover(function(e){
         $("body").append('<div class="tooltip">'+$(this).attr('id')+'</div>');
         $('.tooltip').css({
                     top : e.pageY - 50,
                     left : e.pageX + 20
                     }).fadeIn();
      
   }, function(){
      $('.tooltip').remove();
   }).mousemove(function(e){
      $('.tooltip').css({
                     top : e.pageY - 50,
                     left : e.pageX + 20
                     })
   })
   
});

</script>