<?php
    if(isset($this->flag))
    {
        switch($this->flag)
        {
            case 1:
                echo "<h3>Não é possível deletar um projeto que não esteja concluído!</h3><br>";
                break;
        }
    }
?>

<?php echo $this->headLink()->appendStylesheet('/css/tabela.css')
                           ->appendStylesheet('/css/projetos_css.css');?>

<ul id="globalnav">
  <li><a href="/projeto/index" >Projetos que colaboro</a></li>
  <li><a href="/projeto/gerencio">Projetos que gerencio</a></li>
  <li><a href="#" class="here">Detalhes</a></li>
</ul>
<br/>
<div id="detalhes">
    <div id="projetos_detalhes" style="-moz-box-shadow: 10px 10px 5px #ffb706; /* Firefox 3.6 and earlier */
                                        box-shadow: 0px 5px 10px #ffb706;">
        <div  id="projetos_detalhes_conteudo">
            <h1 style="color: #fd8f12;"><b><?php echo $this->projetoEncontrado->nome; ?></b></h1><br /><br />
            <h3>Alocado na filial: <span style="color: #ff8000;"><?php echo $this->dadosIndex->nomeEmpresa//echo $this->ProjEncontrado->current()->nomeFilialProj; ?></span></h3><br />

            Data de in&iacute;cio: <b><?php echo $this->projetoEncontrado->dataInc; ?></b><br /><br />
            Previs&atilde;o de conclus&atilde;o: <b><?php echo $this->projetoEncontrado->dataFim; ?></b><br /><br />
            Situa&ccedil&atilde;o do projeto: <b><?php echo $this->estadoProj->buscaEstadoProj($this->projetoEncontrado->idprojeto); ?></b><br /><br />
            <b>Gerente: <?php echo $this->funcLogado->nome ?></b><br /><br />
            <br/>
            Descrição:
            <center>
            <div style="border:3px solid #a1a1a1;
                        border-radius:5px; 
                        word-wrap:break-word; width:70%; border: 1px solid #666666; "><?php echo $this->projetoEncontrado->descricao; ?></div><br />
            </center>

            <center>
                <div class="divGerente" style="width: 200px">
                    <a title="editar projeto"href='/projeto/edit/id/<?php echo $this->projetoEncontrado->idprojeto; ?>'>
                        <img src="/images/b_edit.png" width="20px;" height="20px" alt="editar projeto"/></a> |
                    <a title="excluir projeto" href='/projeto/delete/id/<?php echo $this->projetoEncontrado->idprojeto; ?>'>
                        <img src="/images/b_drop.png" width="20px;" height="20px" alt="excluir projeto"/></a>
                </div>
            </center>
        </div>            
    </div>
    
    <!-- div de tarefas -->

    <div id="projetos_detalhes_tarefas">
        <center><h4>Tarefas do Projeto: <?php echo $this->projetoEncontrado->nome; ?></h4></center>
        <br/>
        <center>
            <a title="Gerenciar Tarefas" href='/tarefa/prepara/idProj/<?php echo $this->projetoEncontrado->idprojeto; ?>'>
                <div class="divGerente" style="width: 100px">

                        <img src="/images/b_tblops.png" width="30px;" height="30px" alt="Gerenciar Tarefas"/><br/>
                        Gerenciar Tarefas
                </div>
            </a>
        </center>
        <br/>
        <center>
            <div style="width:95%;">
                <?php if(count($this->paginator) != 0){?>
            <table width="100%" class="tbl">
                <thead><tr><th></th><th>Nome Funcionário</th><th>Descrição</th></thead>
        <?php 
            $indice = 0;
            foreach ( $this->paginator as $auxtipoEstadoTarefaColabProj ):
                $detalhes = "";
                $detalhes = $detalhes."<h3>Estado da Tarefa:</h3>".$auxtipoEstadoTarefaColabProj->tipoDeEstado."<br/><br/>";
                $detalhes = $detalhes."<h3>Descrição:</h3><br/>".$auxtipoEstadoTarefaColabProj->descricaoTarefa."<br/><br/>";
                $detalhes = $detalhes."<h4>Data de Início:</h4> ".$auxtipoEstadoTarefaColabProj->dataInc."<br/>";
                $detalhes = $detalhes."<h4>Data de Fim:</h4> ".$auxtipoEstadoTarefaColabProj->dataFim."<br/>";
                if($indice%2){
                    echo "<tr class='odd' >
                            <td width='3%' align='center'><a rel='tooltip' id='$detalhes'><img src='/images/lente.png' alt='veja mais' height=24px; width=24px; /></a></td>
                            <td width='10%' align='center' ><p style='word-wrap:break-word;'>".$auxtipoEstadoTarefaColabProj->nomeFunc."</p></td>
                            <td width='15%' align='center'>".substr($auxtipoEstadoTarefaColabProj->descricaoTarefa, 0 , 20)."...</td>
                            </tbody>";
                } else {
                    echo "<tr>
                            <td width='3%' align='center'><a rel='tooltip' id='$detalhes'><img src='/images/lente.png' alt='veja mais' height=24px; width=24px; /></a></td>
                            <td width='10%' align='center'><p style='word-wrap:break-word;'>".$auxtipoEstadoTarefaColabProj->nomeFunc."</p></td>
                            <td width='15%' align='center'>".substr($auxtipoEstadoTarefaColabProj->descricaoTarefa, 0 , 20)."...</td>
                        </tr>";
                }
                $indice = $indice + 1;   
            endforeach; ?>
            </table>

            <div>
                <center><?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?></center>
            </div>
            <?php }  else {?>
                <h3>Este projeto ainda não tem tarefas</h3>
            <?php } ?>
            </div>
        </center>

    </div>
    
    <!-- div de colaboradores -->

    <div id="projetos_detalhes_colaboradores">
        <center><h4>Colaboradores do Projeto: <?php echo $this->projetoEncontrado->nome; ?></h4></center>
        <br/>
        <center>
            <a title="Gerenciar Colaboradores" href='/colaborador/index/id/<?php echo $this->projetoEncontrado->idprojeto; ?>' >
                <div class="divGerente" style="width: 200px">
                    <img src="/images/b_tblops.png" width="30px;" height="30px" alt="Gerenciar Colaboradores"/><br/>
                    Gerenciar Colaboradores
                </div>
            </a>
        </center>
        <br>
        <br>
        <center>
            <div style="width:95%;">
            <?php if(count($this->colab) != 0){?>
            <table width="100%" class="tbl">
                <thead><tr><th>Nome Funcionário</th><th>Função</th><th>E-mail</th></thead>
        <?php
            $indice = 0;
            foreach ( $this->colab as $auxfuncaoColabProj ): 
                if($indice%2){
                    echo "<tr class='odd' >
                            <td width='10%'><p style='word-wrap:break-word;'>".$auxfuncaoColabProj->nomeFuncinario."</p></td>
                            <td width='15%' align='center'>".$auxfuncaoColabProj->funcao."</td>
                            <td width='8%' align='center'>".$auxfuncaoColabProj->emailFuncinario."</td>
                        </tr>
                        </tbody>";
                } else {
                    echo "<tr>
                            <td width='10%'><p style='word-wrap:break-word;'>".$auxfuncaoColabProj->nomeFuncinario."</p></td>
                            <td width='15%' align='center'>".$auxfuncaoColabProj->funcao."</td>
                            <td width='8%' align='center'>".$auxfuncaoColabProj->emailFuncinario."</td>
                        </tr>";
                }
                $indice = $indice + 1;   
            endforeach; ?>
            </table>
            <?php }  else {?>
            <h3>Este projeto ainda não tem Colaboradores</h3>
            <?php } ?>
            </div>
        </center>
    </div>
    
</div>

<script>
menu('12');
</script>

<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript">

$(function(){
   
   $("*[rel=tooltip]").hover(function(e){
         $("body").append('<div class="tooltip">'+$(this).attr('id')+'</div>');
         $('.tooltip').css({
                     top : e.pageY - 50,
                     left : e.pageX + 20
                     }).fadeIn();
      
   }, function(){
      $('.tooltip').remove();
   }).mousemove(function(e){
      $('.tooltip').css({
                     top : e.pageY - 50,
                     left : e.pageX + 20
                     })
   })
   
});

</script>