<?php echo $this->headLink()->appendStylesheet('/css/tabela.css')
                           ->appendStylesheet('/css/projetos_css.css'); ?>
<ul id="globalnav">
  <li><a href="/projeto/index" >Projetos que colaboro</a></li>
  <li><a href="#" class="here">Projetos que gerencio</a></li>
</ul>
<br>
<br>
<div id="projetos">
<?php
    if(isset($this->flag))
    {
        switch($this->flag)
        {
            case 1:
                echo "<h3>Você precisa ser gerente do projeto para gerenciar os colaboradores</h3><br>";
                break;
        }
    }
?>


    <br/>
    <?php foreach ( $this->paginator as $aux ) : ?>
        <center>
        <div id="projetos_conteudo">
                Nome: <b><?php echo $aux['nome']; ?></b><br />
                Resumo: <?php echo substr($aux['descricao'], 0, 50)."..."; ?><br />
                Data de in&iacute;cio: <?php echo $aux['dataInc']; ?><br />
                Previs&atilde;o de conclus&atilde;o: <?php echo $aux['dataFim']; ?><br />
                Situa&ccedil&atilde;o do projeto: <?php echo $this->estadoProj->buscaEstadoProj($aux['idprojeto']); ?><br/>
                <b>Gerente: <?php echo $this->funcLogado->nome ?></b><br />
                <br/>
                <a href='/projeto/detalhesgerente/idProj/<?php echo $aux['idprojeto']; ?>'>Acessar Projeto</a>
                <?php if($this->idFuncLogado == $aux['idGerente']){?>
                    | <a href='/tarefa/prepara/idProj/<?php echo $aux['idprojeto']; ?>'>Tarefas do Projeto</a>
                <?php }?>
        </div>
        </center>
    <?php endforeach; ?>
    <br/>
    <div>
    <center><?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?></center>
    </div>
    <br/>
</div>

<script>
menu('12');
</script>