<?php
    if ( isset($this->flag) and !($this->mem)  )
    {
        switch($this->flag)
        {
            case 1:
                echo "<div id='alerta'>Você precisa ser gerente do projeto para gerenciar os colaboradores</div>";
                break;
        }
    }
?>
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery-ui.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $("#alerta").dialog({
                modal : true,
                title : "<span class='ui-icon ui-icon-info' style='float:left; margin:1px 7px 0 0;'></span>Alerta do Sistema",
                resizable : false,
                draggable : false,
                buttons: {
                        Ok: function() {
                                $( this ).dialog( "close" );
                        }
                }
                        
        });
      
});
</script>
<ul id="globalnav">
  <li><a href="/projeto/index" >Projetos que colaboro</a></li>
  <li><a href="#" class="here">Projetos que gerencio</a></li>
</ul>
<br/>
<div id="createproject">
        <?php if(count($this->paginator) == 0){ ?>
        <br/>
        <center><h3>Atualmente, você não gerencia nenhum projeto.</h3></center>
        <?php }?>
        <?php foreach ( $this->paginator as $aux ) : ?>
        <center>
        <div id="projetos_conteudo">
                Nome: <b><?php echo $aux['nome']; ?></b><br />
                Resumo: <?php echo substr($aux['descricao'], 0, 50)."..."; ?><br />
                Data de in&iacute;cio: <?php echo $aux['dataInc']; ?><br />
                
                Situa&ccedil&atilde;o do projeto: <?php echo $this->estadoProj->buscaEstadoProj($aux['idprojeto']); ?><br/>
                <?php if($this->estadoProj->buscaEstadoProj($aux['idprojeto']) == "Concluido"){ ?>
                    Data de Término: <?php echo $aux['dataFim']; ?><br />
                <?php }?>
                <b>Gerente: <?php echo $this->funcLogado->nome ?></b><br />
                <br/>
                <a href='/projeto/detalhesgerente/idProj/<?php echo $aux['idprojeto']; ?>'>Acessar Projeto</a>
                <?php if($this->idFuncLogado == $aux['idGerente']){?>
                    | <a href='/tarefa/prepara/idProj/<?php echo $aux['idprojeto']; ?>'>Tarefas do Projeto</a>
                <?php }?>
        </div>
        </center>
    <?php endforeach; ?>
    <br/>
    <div>
    <center><?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?></center>
    </div>
    <br/>
</div>

<script>
menu('12');
</script>