<?php
    if(isset($this->flag))
    {
        switch($this->flag)
        {
            case 1:
                echo "<h3>Você precisa ser gerente do projeto para gerenciar os colaboradores</h3><br>";
                break;
            case 2:
                echo "<h3>Projeto editado com sucesso</h3><br>";
                break;
            case 3:
                echo "<h3>Projeto inserido com sucesso</h3><br>";
                break;
            case 4:
                echo "<h3>Projeto excluido com sucesso</h3><br>";
                break;
        }
    }
?>

<ul id="globalnav">
  <li><a href="#" class="here">Projetos que colaboro</a></li>
  <li><a href="/projeto/gerencio">Projetos que gerencio</a></li>
</ul>

<div id="createproject">
    <?php foreach ( $this->paginator as $aux ) : ?>
        <center>
        <div id="projetos_conteudo"
        <?php if($this->idFuncLogado == $aux['idGerente']){?>
            style="-moz-box-shadow: 10px 10px 5px #ffb706; /* Firefox 3.6 and earlier */
                    box-shadow: 0px 5px 10px #ffb706;"
        <?php } ?>     
        >
                Nome: <b><?php echo $aux['nomeProj']; ?></b><br />
                Resumo: <?php echo substr($aux['descricaoProj'], 0, 50)."..."; ?><br />
                Data de in&iacute;cio: <?php echo $aux['dataInc']; ?><br />
                Previs&atilde;o de conclus&atilde;o: <?php echo $aux['dataFim']; ?><br />
                Situa&ccedil&atilde;o do projeto: <?php echo $aux['estadoProj']; ?><br/>
               
                <?php if($this->idFuncLogado == $aux['idGerente']){?>
                    <b>Gerente: <?php echo $aux['nomeGerente']; ?></b><br />
                <?php }else{ ?>
                     Gerente: <?php echo $aux['nomeGerente']; ?><br />
                <?php } ?>
                <br/>
                <a href='/projeto/detalhes/idProj/<?php echo $aux['idprojeto']; ?>'>Acessar Projeto</a>
                <?php if($this->idFuncLogado == $aux['idGerente']){?>
                    | <a href='/tarefa/prepara/idProj/<?php echo $aux['idprojeto']; ?>'>Tarefas do Projeto</a>
                <?php }?>
        </div>
        </center>
    <?php endforeach; ?>
    <br/>
    <div>
    <center><?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?></center>
    </div>
    <br/>
</div>

<script>
menu('12');
</script>