<?php echo $this->headLink()->appendStylesheet('/css/tabela.css') ?>
<br/>
<br/>
<div style="border: 1px solid #666666; overflow:scroll; width:100%; height:400px;">
    <br/>
    <center><h2>Seus Projetos</h2></center>
    <br/>
    <?php foreach ( $this->paginator as $aux ) : ?>
        <center>
        <div style="margin: 5px; text-align:center; width:80%; border: 1px solid #666666;">
                Nome: <?php echo $aux['nomeProj']; ?><br />
                Resumo: <?php echo substr($aux['descricaoProj'], 0, 50)."..."; ?><br />
                Data de in&iacute;cio: <?php echo $aux['dataInc']; ?><br />
                Previs&atilde;o de conclus&atilde;o: <?php echo $aux['dataFim']; ?><br />
                Situa&ccedil&atilde;o do projeto: <?php echo $aux['estadoProj']; ?><br/>
                Gerente: <?php echo $aux['nomeGerente']; ?>
                <br/>
                <a href='/projeto/detalhes/idProj/<?php echo $aux['idprojeto']; ?>'>Acessar Projeto</a>
                <?php if($this->idFuncLogado == $aux['idGerente']){?>
                    | <a href='/tarefa/prepara/idProj/<?php echo $aux['idprojeto']; ?>'>Tarefas do Projeto</a>
                <?php }?>
        </div>
        </center>
    <?php endforeach; ?>
    <div>
    <center><?= $this->paginationControl($this->p, 'Sliding', 'my_pagination_control.phtml');?></center>
    </div>
</div>

<script>
menu('12');
</script>